import type { Address, Hex, Log } from 'viem';

export const AttestationValidatorAbi = [
  {
    type: 'constructor',
    inputs: [
      { name: '_taskManager', type: 'address', internalType: 'address' },
      { name: '_operatorRegistry', type: 'address', internalType: 'address' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'attestationExpirations',
    inputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    outputs: [{ name: '', type: 'uint32', internalType: 'uint32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'attestationHash',
    inputs: [{ name: 'taskId', type: 'bytes32', internalType: 'bytes32' }],
    outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'attestations',
    inputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'createAttestationHash',
    inputs: [
      { name: 'taskId', type: 'bytes32', internalType: 'bytes32' },
      { name: 'policyId', type: 'bytes32', internalType: 'bytes32' },
      { name: 'policyClient', type: 'address', internalType: 'address' },
      {
        name: 'intent',
        type: 'tuple',
        internalType: 'struct NewtonMessage.Intent',
        components: [
          { name: 'from', type: 'address', internalType: 'address' },
          { name: 'to', type: 'address', internalType: 'address' },
          { name: 'value', type: 'uint256', internalType: 'uint256' },
          { name: 'data', type: 'bytes', internalType: 'bytes' },
          { name: 'chainId', type: 'uint256', internalType: 'uint256' },
          { name: 'functionSignature', type: 'bytes', internalType: 'bytes' },
        ],
      },
      { name: 'intentSignature', type: 'bytes', internalType: 'bytes' },
      { name: 'expiration', type: 'uint32', internalType: 'uint32' },
    ],
    outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'directlyVerifiedAttestations',
    inputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'initialize',
    inputs: [{ name: '_owner', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'invalidateAttestation',
    inputs: [{ name: 'taskId', type: 'bytes32', internalType: 'bytes32' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'isAttestationValid',
    inputs: [
      {
        name: 'attestation',
        type: 'tuple',
        internalType: 'struct NewtonMessage.Attestation',
        components: [
          { name: 'taskId', type: 'bytes32', internalType: 'bytes32' },
          { name: 'policyId', type: 'bytes32', internalType: 'bytes32' },
          { name: 'policyClient', type: 'address', internalType: 'address' },
          { name: 'expiration', type: 'uint32', internalType: 'uint32' },
          {
            name: 'intent',
            type: 'tuple',
            internalType: 'struct NewtonMessage.Intent',
            components: [
              { name: 'from', type: 'address', internalType: 'address' },
              { name: 'to', type: 'address', internalType: 'address' },
              { name: 'value', type: 'uint256', internalType: 'uint256' },
              { name: 'data', type: 'bytes', internalType: 'bytes' },
              { name: 'chainId', type: 'uint256', internalType: 'uint256' },
              { name: 'functionSignature', type: 'bytes', internalType: 'bytes' },
            ],
          },
          { name: 'intentSignature', type: 'bytes', internalType: 'bytes' },
        ],
      },
    ],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'isDirectlyVerified',
    inputs: [{ name: 'taskId', type: 'bytes32', internalType: 'bytes32' }],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'markDirectlyVerified',
    inputs: [{ name: 'taskId', type: 'bytes32', internalType: 'bytes32' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'operatorRegistry',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'owner',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  { type: 'function', name: 'renounceOwnership', inputs: [], outputs: [], stateMutability: 'nonpayable' },
  {
    type: 'function',
    name: 'taskManager',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'transferOwnership',
    inputs: [{ name: 'newOwner', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'validateAttestation',
    inputs: [
      {
        name: 'attestation',
        type: 'tuple',
        internalType: 'struct NewtonMessage.Attestation',
        components: [
          { name: 'taskId', type: 'bytes32', internalType: 'bytes32' },
          { name: 'policyId', type: 'bytes32', internalType: 'bytes32' },
          { name: 'policyClient', type: 'address', internalType: 'address' },
          { name: 'expiration', type: 'uint32', internalType: 'uint32' },
          {
            name: 'intent',
            type: 'tuple',
            internalType: 'struct NewtonMessage.Intent',
            components: [
              { name: 'from', type: 'address', internalType: 'address' },
              { name: 'to', type: 'address', internalType: 'address' },
              { name: 'value', type: 'uint256', internalType: 'uint256' },
              { name: 'data', type: 'bytes', internalType: 'bytes' },
              { name: 'chainId', type: 'uint256', internalType: 'uint256' },
              { name: 'functionSignature', type: 'bytes', internalType: 'bytes' },
            ],
          },
          { name: 'intentSignature', type: 'bytes', internalType: 'bytes' },
        ],
      },
    ],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'validateAttestationDirect',
    inputs: [
      {
        name: 'task',
        type: 'tuple',
        internalType: 'struct INewtonProverTaskManager.Task',
        components: [
          { name: 'taskId', type: 'bytes32', internalType: 'bytes32' },
          { name: 'policyId', type: 'bytes32', internalType: 'bytes32' },
          { name: 'policyClient', type: 'address', internalType: 'address' },
          { name: 'nonce', type: 'uint32', internalType: 'uint32' },
          { name: 'taskCreatedBlock', type: 'uint32', internalType: 'uint32' },
          { name: 'quorumThresholdPercentage', type: 'uint32', internalType: 'uint32' },
          {
            name: 'intent',
            type: 'tuple',
            internalType: 'struct NewtonMessage.Intent',
            components: [
              { name: 'from', type: 'address', internalType: 'address' },
              { name: 'to', type: 'address', internalType: 'address' },
              { name: 'value', type: 'uint256', internalType: 'uint256' },
              { name: 'data', type: 'bytes', internalType: 'bytes' },
              { name: 'chainId', type: 'uint256', internalType: 'uint256' },
              { name: 'functionSignature', type: 'bytes', internalType: 'bytes' },
            ],
          },
          { name: 'intentSignature', type: 'bytes', internalType: 'bytes' },
          {
            name: 'policyTaskData',
            type: 'tuple',
            internalType: 'struct NewtonMessage.PolicyTaskData',
            components: [
              { name: 'policyId', type: 'bytes32', internalType: 'bytes32' },
              { name: 'policyAddress', type: 'address', internalType: 'address' },
              { name: 'policy', type: 'bytes', internalType: 'bytes' },
              {
                name: 'policyData',
                type: 'tuple[]',
                internalType: 'struct NewtonMessage.PolicyData[]',
                components: [
                  { name: 'wasmArgs', type: 'bytes', internalType: 'bytes' },
                  { name: 'data', type: 'bytes', internalType: 'bytes' },
                  { name: 'attestation', type: 'bytes', internalType: 'bytes' },
                  { name: 'policyDataAddress', type: 'address', internalType: 'address' },
                  { name: 'expireBlock', type: 'uint32', internalType: 'uint32' },
                ],
              },
            ],
          },
          {
            name: 'policyConfig',
            type: 'tuple',
            internalType: 'struct INewtonPolicy.PolicyConfig',
            components: [
              { name: 'policyParams', type: 'bytes', internalType: 'bytes' },
              { name: 'expireAfter', type: 'uint32', internalType: 'uint32' },
            ],
          },
          { name: 'quorumNumbers', type: 'bytes', internalType: 'bytes' },
        ],
      },
      {
        name: 'taskResponse',
        type: 'tuple',
        internalType: 'struct INewtonProverTaskManager.TaskResponse',
        components: [
          { name: 'taskId', type: 'bytes32', internalType: 'bytes32' },
          { name: 'policyClient', type: 'address', internalType: 'address' },
          { name: 'policyId', type: 'bytes32', internalType: 'bytes32' },
          { name: 'policyAddress', type: 'address', internalType: 'address' },
          {
            name: 'intent',
            type: 'tuple',
            internalType: 'struct NewtonMessage.Intent',
            components: [
              { name: 'from', type: 'address', internalType: 'address' },
              { name: 'to', type: 'address', internalType: 'address' },
              { name: 'value', type: 'uint256', internalType: 'uint256' },
              { name: 'data', type: 'bytes', internalType: 'bytes' },
              { name: 'chainId', type: 'uint256', internalType: 'uint256' },
              { name: 'functionSignature', type: 'bytes', internalType: 'bytes' },
            ],
          },
          { name: 'intentSignature', type: 'bytes', internalType: 'bytes' },
          { name: 'evaluationResult', type: 'bytes', internalType: 'bytes' },
        ],
      },
      {
        name: 'nonSignerStakesAndSignature',
        type: 'tuple',
        internalType: 'struct IBLSSignatureCheckerTypes.NonSignerStakesAndSignature',
        components: [
          { name: 'nonSignerQuorumBitmapIndices', type: 'uint32[]', internalType: 'uint32[]' },
          {
            name: 'nonSignerPubkeys',
            type: 'tuple[]',
            internalType: 'struct BN254.G1Point[]',
            components: [
              { name: 'X', type: 'uint256', internalType: 'uint256' },
              { name: 'Y', type: 'uint256', internalType: 'uint256' },
            ],
          },
          {
            name: 'quorumApks',
            type: 'tuple[]',
            internalType: 'struct BN254.G1Point[]',
            components: [
              { name: 'X', type: 'uint256', internalType: 'uint256' },
              { name: 'Y', type: 'uint256', internalType: 'uint256' },
            ],
          },
          {
            name: 'apkG2',
            type: 'tuple',
            internalType: 'struct BN254.G2Point',
            components: [
              { name: 'X', type: 'uint256[2]', internalType: 'uint256[2]' },
              { name: 'Y', type: 'uint256[2]', internalType: 'uint256[2]' },
            ],
          },
          {
            name: 'sigma',
            type: 'tuple',
            internalType: 'struct BN254.G1Point',
            components: [
              { name: 'X', type: 'uint256', internalType: 'uint256' },
              { name: 'Y', type: 'uint256', internalType: 'uint256' },
            ],
          },
          { name: 'quorumApkIndices', type: 'uint32[]', internalType: 'uint32[]' },
          { name: 'totalStakeIndices', type: 'uint32[]', internalType: 'uint32[]' },
          { name: 'nonSignerStakeIndices', type: 'uint32[][]', internalType: 'uint32[][]' },
        ],
      },
      {
        name: 'checkSignatures',
        type: 'function',
        internalType:
          'function (bytes32,bytes,uint32,struct IBLSSignatureCheckerTypes.NonSignerStakesAndSignature) view external returns (struct IBLSSignatureCheckerTypes.QuorumStakeTotals,bytes32)',
      },
    ],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    name: 'Initialized',
    inputs: [{ name: 'version', type: 'uint8', indexed: false, internalType: 'uint8' }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'OwnershipTransferred',
    inputs: [
      { name: 'previousOwner', type: 'address', indexed: true, internalType: 'address' },
      { name: 'newOwner', type: 'address', indexed: true, internalType: 'address' },
    ],
    anonymous: false,
  },
  { type: 'error', name: 'AttestationAlreadySpent', inputs: [] },
  { type: 'error', name: 'AttestationExpired', inputs: [] },
  { type: 'error', name: 'AttestationHashMismatch', inputs: [] },
  { type: 'error', name: 'OnlyTaskManager', inputs: [] },
  { type: 'error', name: 'PolicyNotVerified', inputs: [] },
  {
    type: 'error',
    name: 'TaskMismatch',
    inputs: [
      { name: 'expected', type: 'bytes32', internalType: 'bytes32' },
      { name: 'actual', type: 'bytes32', internalType: 'bytes32' },
    ],
  },
];

export const NewtonProverTaskManagerAbi = [
  {
    type: 'constructor',
    inputs: [
      { name: '_operatorRegistry', type: 'address', internalType: 'contract OperatorRegistry' },
      { name: '_pauserRegistry', type: 'address', internalType: 'contract IPauserRegistry' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'aggregator',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'allTaskHashes',
    inputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'allTaskResponses',
    inputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'attestationValidator',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'blsApkRegistry',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IBLSApkRegistry' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'certificateVerifier',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'challengeDirectlyVerifiedAttestation',
    inputs: [
      {
        name: 'task',
        type: 'tuple',
        internalType: 'struct INewtonProverTaskManager.Task',
        components: [
          { name: 'taskId', type: 'bytes32', internalType: 'bytes32' },
          { name: 'policyId', type: 'bytes32', internalType: 'bytes32' },
          { name: 'policyClient', type: 'address', internalType: 'address' },
          { name: 'nonce', type: 'uint32', internalType: 'uint32' },
          { name: 'taskCreatedBlock', type: 'uint32', internalType: 'uint32' },
          { name: 'quorumThresholdPercentage', type: 'uint32', internalType: 'uint32' },
          {
            name: 'intent',
            type: 'tuple',
            internalType: 'struct NewtonMessage.Intent',
            components: [
              { name: 'from', type: 'address', internalType: 'address' },
              { name: 'to', type: 'address', internalType: 'address' },
              { name: 'value', type: 'uint256', internalType: 'uint256' },
              { name: 'data', type: 'bytes', internalType: 'bytes' },
              { name: 'chainId', type: 'uint256', internalType: 'uint256' },
              { name: 'functionSignature', type: 'bytes', internalType: 'bytes' },
            ],
          },
          { name: 'intentSignature', type: 'bytes', internalType: 'bytes' },
          {
            name: 'policyTaskData',
            type: 'tuple',
            internalType: 'struct NewtonMessage.PolicyTaskData',
            components: [
              { name: 'policyId', type: 'bytes32', internalType: 'bytes32' },
              { name: 'policyAddress', type: 'address', internalType: 'address' },
              { name: 'policy', type: 'bytes', internalType: 'bytes' },
              {
                name: 'policyData',
                type: 'tuple[]',
                internalType: 'struct NewtonMessage.PolicyData[]',
                components: [
                  { name: 'wasmArgs', type: 'bytes', internalType: 'bytes' },
                  { name: 'data', type: 'bytes', internalType: 'bytes' },
                  { name: 'attestation', type: 'bytes', internalType: 'bytes' },
                  { name: 'policyDataAddress', type: 'address', internalType: 'address' },
                  { name: 'expireBlock', type: 'uint32', internalType: 'uint32' },
                ],
              },
            ],
          },
          {
            name: 'policyConfig',
            type: 'tuple',
            internalType: 'struct INewtonPolicy.PolicyConfig',
            components: [
              { name: 'policyParams', type: 'bytes', internalType: 'bytes' },
              { name: 'expireAfter', type: 'uint32', internalType: 'uint32' },
            ],
          },
          { name: 'quorumNumbers', type: 'bytes', internalType: 'bytes' },
        ],
      },
      {
        name: 'taskResponse',
        type: 'tuple',
        internalType: 'struct INewtonProverTaskManager.TaskResponse',
        components: [
          { name: 'taskId', type: 'bytes32', internalType: 'bytes32' },
          { name: 'policyClient', type: 'address', internalType: 'address' },
          { name: 'policyId', type: 'bytes32', internalType: 'bytes32' },
          { name: 'policyAddress', type: 'address', internalType: 'address' },
          {
            name: 'intent',
            type: 'tuple',
            internalType: 'struct NewtonMessage.Intent',
            components: [
              { name: 'from', type: 'address', internalType: 'address' },
              { name: 'to', type: 'address', internalType: 'address' },
              { name: 'value', type: 'uint256', internalType: 'uint256' },
              { name: 'data', type: 'bytes', internalType: 'bytes' },
              { name: 'chainId', type: 'uint256', internalType: 'uint256' },
              { name: 'functionSignature', type: 'bytes', internalType: 'bytes' },
            ],
          },
          { name: 'intentSignature', type: 'bytes', internalType: 'bytes' },
          { name: 'evaluationResult', type: 'bytes', internalType: 'bytes' },
        ],
      },
      {
        name: 'nonSignerStakesAndSignature',
        type: 'tuple',
        internalType: 'struct IBLSSignatureCheckerTypes.NonSignerStakesAndSignature',
        components: [
          { name: 'nonSignerQuorumBitmapIndices', type: 'uint32[]', internalType: 'uint32[]' },
          {
            name: 'nonSignerPubkeys',
            type: 'tuple[]',
            internalType: 'struct BN254.G1Point[]',
            components: [
              { name: 'X', type: 'uint256', internalType: 'uint256' },
              { name: 'Y', type: 'uint256', internalType: 'uint256' },
            ],
          },
          {
            name: 'quorumApks',
            type: 'tuple[]',
            internalType: 'struct BN254.G1Point[]',
            components: [
              { name: 'X', type: 'uint256', internalType: 'uint256' },
              { name: 'Y', type: 'uint256', internalType: 'uint256' },
            ],
          },
          {
            name: 'apkG2',
            type: 'tuple',
            internalType: 'struct BN254.G2Point',
            components: [
              { name: 'X', type: 'uint256[2]', internalType: 'uint256[2]' },
              { name: 'Y', type: 'uint256[2]', internalType: 'uint256[2]' },
            ],
          },
          {
            name: 'sigma',
            type: 'tuple',
            internalType: 'struct BN254.G1Point',
            components: [
              { name: 'X', type: 'uint256', internalType: 'uint256' },
              { name: 'Y', type: 'uint256', internalType: 'uint256' },
            ],
          },
          { name: 'quorumApkIndices', type: 'uint32[]', internalType: 'uint32[]' },
          { name: 'totalStakeIndices', type: 'uint32[]', internalType: 'uint32[]' },
          { name: 'nonSignerStakeIndices', type: 'uint32[][]', internalType: 'uint32[][]' },
        ],
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'challengeVerifier',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'checkSignatures',
    inputs: [
      { name: 'msgHash', type: 'bytes32', internalType: 'bytes32' },
      { name: 'quorumNumbers', type: 'bytes', internalType: 'bytes' },
      { name: 'referenceBlockNumber', type: 'uint32', internalType: 'uint32' },
      {
        name: 'params',
        type: 'tuple',
        internalType: 'struct IBLSSignatureCheckerTypes.NonSignerStakesAndSignature',
        components: [
          { name: 'nonSignerQuorumBitmapIndices', type: 'uint32[]', internalType: 'uint32[]' },
          {
            name: 'nonSignerPubkeys',
            type: 'tuple[]',
            internalType: 'struct BN254.G1Point[]',
            components: [
              { name: 'X', type: 'uint256', internalType: 'uint256' },
              { name: 'Y', type: 'uint256', internalType: 'uint256' },
            ],
          },
          {
            name: 'quorumApks',
            type: 'tuple[]',
            internalType: 'struct BN254.G1Point[]',
            components: [
              { name: 'X', type: 'uint256', internalType: 'uint256' },
              { name: 'Y', type: 'uint256', internalType: 'uint256' },
            ],
          },
          {
            name: 'apkG2',
            type: 'tuple',
            internalType: 'struct BN254.G2Point',
            components: [
              { name: 'X', type: 'uint256[2]', internalType: 'uint256[2]' },
              { name: 'Y', type: 'uint256[2]', internalType: 'uint256[2]' },
            ],
          },
          {
            name: 'sigma',
            type: 'tuple',
            internalType: 'struct BN254.G1Point',
            components: [
              { name: 'X', type: 'uint256', internalType: 'uint256' },
              { name: 'Y', type: 'uint256', internalType: 'uint256' },
            ],
          },
          { name: 'quorumApkIndices', type: 'uint32[]', internalType: 'uint32[]' },
          { name: 'totalStakeIndices', type: 'uint32[]', internalType: 'uint32[]' },
          { name: 'nonSignerStakeIndices', type: 'uint32[][]', internalType: 'uint32[][]' },
        ],
      },
    ],
    outputs: [
      {
        name: '',
        type: 'tuple',
        internalType: 'struct IBLSSignatureCheckerTypes.QuorumStakeTotals',
        components: [
          { name: 'signedStakeForQuorum', type: 'uint96[]', internalType: 'uint96[]' },
          { name: 'totalStakeForQuorum', type: 'uint96[]', internalType: 'uint96[]' },
        ],
      },
      { name: '', type: 'bytes32', internalType: 'bytes32' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'createNewTask',
    inputs: [
      {
        name: 'params',
        type: 'tuple',
        internalType: 'struct INewtonProverTaskManager.TaskParams',
        components: [
          { name: 'taskId', type: 'bytes32', internalType: 'bytes32' },
          { name: 'wasmArgs', type: 'bytes', internalType: 'bytes' },
          { name: 'policyClient', type: 'address', internalType: 'address' },
          {
            name: 'intent',
            type: 'tuple',
            internalType: 'struct NewtonMessage.Intent',
            components: [
              { name: 'from', type: 'address', internalType: 'address' },
              { name: 'to', type: 'address', internalType: 'address' },
              { name: 'value', type: 'uint256', internalType: 'uint256' },
              { name: 'data', type: 'bytes', internalType: 'bytes' },
              { name: 'chainId', type: 'uint256', internalType: 'uint256' },
              { name: 'functionSignature', type: 'bytes', internalType: 'bytes' },
            ],
          },
          { name: 'intentSignature', type: 'bytes', internalType: 'bytes' },
          {
            name: 'policyTaskData',
            type: 'tuple',
            internalType: 'struct NewtonMessage.PolicyTaskData',
            components: [
              { name: 'policyId', type: 'bytes32', internalType: 'bytes32' },
              { name: 'policyAddress', type: 'address', internalType: 'address' },
              { name: 'policy', type: 'bytes', internalType: 'bytes' },
              {
                name: 'policyData',
                type: 'tuple[]',
                internalType: 'struct NewtonMessage.PolicyData[]',
                components: [
                  { name: 'wasmArgs', type: 'bytes', internalType: 'bytes' },
                  { name: 'data', type: 'bytes', internalType: 'bytes' },
                  { name: 'attestation', type: 'bytes', internalType: 'bytes' },
                  { name: 'policyDataAddress', type: 'address', internalType: 'address' },
                  { name: 'expireBlock', type: 'uint32', internalType: 'uint32' },
                ],
              },
            ],
          },
          { name: 'quorumNumbers', type: 'bytes', internalType: 'bytes' },
          { name: 'quorumThresholdPercentage', type: 'uint32', internalType: 'uint32' },
        ],
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'delegation',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IDelegationManager' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getBatchOperatorFromId',
    inputs: [
      { name: 'registryCoordinator', type: 'address', internalType: 'contract ISlashingRegistryCoordinator' },
      { name: 'operatorIds', type: 'bytes32[]', internalType: 'bytes32[]' },
    ],
    outputs: [{ name: 'operators', type: 'address[]', internalType: 'address[]' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getBatchOperatorId',
    inputs: [
      { name: 'registryCoordinator', type: 'address', internalType: 'contract ISlashingRegistryCoordinator' },
      { name: 'operators', type: 'address[]', internalType: 'address[]' },
    ],
    outputs: [{ name: 'operatorIds', type: 'bytes32[]', internalType: 'bytes32[]' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getCheckSignaturesIndices',
    inputs: [
      { name: 'registryCoordinator', type: 'address', internalType: 'contract ISlashingRegistryCoordinator' },
      { name: 'referenceBlockNumber', type: 'uint32', internalType: 'uint32' },
      { name: 'quorumNumbers', type: 'bytes', internalType: 'bytes' },
      { name: 'nonSignerOperatorIds', type: 'bytes32[]', internalType: 'bytes32[]' },
    ],
    outputs: [
      {
        name: '',
        type: 'tuple',
        internalType: 'struct OperatorStateRetriever.CheckSignaturesIndices',
        components: [
          { name: 'nonSignerQuorumBitmapIndices', type: 'uint32[]', internalType: 'uint32[]' },
          { name: 'quorumApkIndices', type: 'uint32[]', internalType: 'uint32[]' },
          { name: 'totalStakeIndices', type: 'uint32[]', internalType: 'uint32[]' },
          { name: 'nonSignerStakeIndices', type: 'uint32[][]', internalType: 'uint32[][]' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getOperatorState',
    inputs: [
      { name: 'registryCoordinator', type: 'address', internalType: 'contract ISlashingRegistryCoordinator' },
      { name: 'quorumNumbers', type: 'bytes', internalType: 'bytes' },
      { name: 'blockNumber', type: 'uint32', internalType: 'uint32' },
    ],
    outputs: [
      {
        name: '',
        type: 'tuple[][]',
        internalType: 'struct OperatorStateRetriever.Operator[][]',
        components: [
          { name: 'operator', type: 'address', internalType: 'address' },
          { name: 'operatorId', type: 'bytes32', internalType: 'bytes32' },
          { name: 'stake', type: 'uint96', internalType: 'uint96' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getOperatorState',
    inputs: [
      { name: 'registryCoordinator', type: 'address', internalType: 'contract ISlashingRegistryCoordinator' },
      { name: 'operatorId', type: 'bytes32', internalType: 'bytes32' },
      { name: 'blockNumber', type: 'uint32', internalType: 'uint32' },
    ],
    outputs: [
      { name: '', type: 'uint256', internalType: 'uint256' },
      {
        name: '',
        type: 'tuple[][]',
        internalType: 'struct OperatorStateRetriever.Operator[][]',
        components: [
          { name: 'operator', type: 'address', internalType: 'address' },
          { name: 'operatorId', type: 'bytes32', internalType: 'bytes32' },
          { name: 'stake', type: 'uint96', internalType: 'uint96' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getQuorumBitmapsAtBlockNumber',
    inputs: [
      { name: 'registryCoordinator', type: 'address', internalType: 'contract ISlashingRegistryCoordinator' },
      { name: 'operatorIds', type: 'bytes32[]', internalType: 'bytes32[]' },
      { name: 'blockNumber', type: 'uint32', internalType: 'uint32' },
    ],
    outputs: [{ name: '', type: 'uint256[]', internalType: 'uint256[]' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'initialize',
    inputs: [
      { name: 'initialOwner', type: 'address', internalType: 'address' },
      { name: '_aggregator', type: 'address', internalType: 'address' },
      { name: '_serviceManager', type: 'address', internalType: 'address' },
      { name: '_operatorRegistry', type: 'address', internalType: 'address' },
      { name: '_taskResponseHandler', type: 'address', internalType: 'address' },
      { name: '_challengeVerifier', type: 'address', internalType: 'address' },
      { name: '_attestationValidator', type: 'address', internalType: 'address' },
      { name: '_taskResponseWindowBlock', type: 'uint32', internalType: 'uint32' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'isDestinationChain',
    inputs: [],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'nonce',
    inputs: [],
    outputs: [{ name: '', type: 'uint32', internalType: 'uint32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'operatorRegistry',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'owner',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'pause',
    inputs: [{ name: 'newPausedStatus', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  { type: 'function', name: 'pauseAll', inputs: [], outputs: [], stateMutability: 'nonpayable' },
  {
    type: 'function',
    name: 'paused',
    inputs: [{ name: 'index', type: 'uint8', internalType: 'uint8' }],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'paused',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'pauserRegistry',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IPauserRegistry' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'raiseAndResolveChallenge',
    inputs: [
      {
        name: 'task',
        type: 'tuple',
        internalType: 'struct INewtonProverTaskManager.Task',
        components: [
          { name: 'taskId', type: 'bytes32', internalType: 'bytes32' },
          { name: 'policyId', type: 'bytes32', internalType: 'bytes32' },
          { name: 'policyClient', type: 'address', internalType: 'address' },
          { name: 'nonce', type: 'uint32', internalType: 'uint32' },
          { name: 'taskCreatedBlock', type: 'uint32', internalType: 'uint32' },
          { name: 'quorumThresholdPercentage', type: 'uint32', internalType: 'uint32' },
          {
            name: 'intent',
            type: 'tuple',
            internalType: 'struct NewtonMessage.Intent',
            components: [
              { name: 'from', type: 'address', internalType: 'address' },
              { name: 'to', type: 'address', internalType: 'address' },
              { name: 'value', type: 'uint256', internalType: 'uint256' },
              { name: 'data', type: 'bytes', internalType: 'bytes' },
              { name: 'chainId', type: 'uint256', internalType: 'uint256' },
              { name: 'functionSignature', type: 'bytes', internalType: 'bytes' },
            ],
          },
          { name: 'intentSignature', type: 'bytes', internalType: 'bytes' },
          {
            name: 'policyTaskData',
            type: 'tuple',
            internalType: 'struct NewtonMessage.PolicyTaskData',
            components: [
              { name: 'policyId', type: 'bytes32', internalType: 'bytes32' },
              { name: 'policyAddress', type: 'address', internalType: 'address' },
              { name: 'policy', type: 'bytes', internalType: 'bytes' },
              {
                name: 'policyData',
                type: 'tuple[]',
                internalType: 'struct NewtonMessage.PolicyData[]',
                components: [
                  { name: 'wasmArgs', type: 'bytes', internalType: 'bytes' },
                  { name: 'data', type: 'bytes', internalType: 'bytes' },
                  { name: 'attestation', type: 'bytes', internalType: 'bytes' },
                  { name: 'policyDataAddress', type: 'address', internalType: 'address' },
                  { name: 'expireBlock', type: 'uint32', internalType: 'uint32' },
                ],
              },
            ],
          },
          {
            name: 'policyConfig',
            type: 'tuple',
            internalType: 'struct INewtonPolicy.PolicyConfig',
            components: [
              { name: 'policyParams', type: 'bytes', internalType: 'bytes' },
              { name: 'expireAfter', type: 'uint32', internalType: 'uint32' },
            ],
          },
          { name: 'quorumNumbers', type: 'bytes', internalType: 'bytes' },
        ],
      },
      {
        name: 'taskResponse',
        type: 'tuple',
        internalType: 'struct INewtonProverTaskManager.TaskResponse',
        components: [
          { name: 'taskId', type: 'bytes32', internalType: 'bytes32' },
          { name: 'policyClient', type: 'address', internalType: 'address' },
          { name: 'policyId', type: 'bytes32', internalType: 'bytes32' },
          { name: 'policyAddress', type: 'address', internalType: 'address' },
          {
            name: 'intent',
            type: 'tuple',
            internalType: 'struct NewtonMessage.Intent',
            components: [
              { name: 'from', type: 'address', internalType: 'address' },
              { name: 'to', type: 'address', internalType: 'address' },
              { name: 'value', type: 'uint256', internalType: 'uint256' },
              { name: 'data', type: 'bytes', internalType: 'bytes' },
              { name: 'chainId', type: 'uint256', internalType: 'uint256' },
              { name: 'functionSignature', type: 'bytes', internalType: 'bytes' },
            ],
          },
          { name: 'intentSignature', type: 'bytes', internalType: 'bytes' },
          { name: 'evaluationResult', type: 'bytes', internalType: 'bytes' },
        ],
      },
      {
        name: 'responseCertificate',
        type: 'tuple',
        internalType: 'struct INewtonProverTaskManager.ResponseCertificate',
        components: [
          { name: 'referenceBlock', type: 'uint32', internalType: 'uint32' },
          { name: 'responseExpireBlock', type: 'uint32', internalType: 'uint32' },
          { name: 'hashOfNonSigners', type: 'bytes32', internalType: 'bytes32' },
          {
            name: 'nonSignerStakesAndSignature',
            type: 'tuple',
            internalType: 'struct IBLSSignatureCheckerTypes.NonSignerStakesAndSignature',
            components: [
              { name: 'nonSignerQuorumBitmapIndices', type: 'uint32[]', internalType: 'uint32[]' },
              {
                name: 'nonSignerPubkeys',
                type: 'tuple[]',
                internalType: 'struct BN254.G1Point[]',
                components: [
                  { name: 'X', type: 'uint256', internalType: 'uint256' },
                  { name: 'Y', type: 'uint256', internalType: 'uint256' },
                ],
              },
              {
                name: 'quorumApks',
                type: 'tuple[]',
                internalType: 'struct BN254.G1Point[]',
                components: [
                  { name: 'X', type: 'uint256', internalType: 'uint256' },
                  { name: 'Y', type: 'uint256', internalType: 'uint256' },
                ],
              },
              {
                name: 'apkG2',
                type: 'tuple',
                internalType: 'struct BN254.G2Point',
                components: [
                  { name: 'X', type: 'uint256[2]', internalType: 'uint256[2]' },
                  { name: 'Y', type: 'uint256[2]', internalType: 'uint256[2]' },
                ],
              },
              {
                name: 'sigma',
                type: 'tuple',
                internalType: 'struct BN254.G1Point',
                components: [
                  { name: 'X', type: 'uint256', internalType: 'uint256' },
                  { name: 'Y', type: 'uint256', internalType: 'uint256' },
                ],
              },
              { name: 'quorumApkIndices', type: 'uint32[]', internalType: 'uint32[]' },
              { name: 'totalStakeIndices', type: 'uint32[]', internalType: 'uint32[]' },
              { name: 'nonSignerStakeIndices', type: 'uint32[][]', internalType: 'uint32[][]' },
            ],
          },
        ],
      },
      {
        name: 'challenge',
        type: 'tuple',
        internalType: 'struct INewtonProverTaskManager.ChallengeData',
        components: [
          { name: 'taskId', type: 'bytes32', internalType: 'bytes32' },
          { name: 'proof', type: 'bytes', internalType: 'bytes' },
          { name: 'data', type: 'bytes', internalType: 'bytes' },
        ],
      },
      {
        name: 'pubkeysOfNonSigningOperators',
        type: 'tuple[]',
        internalType: 'struct BN254.G1Point[]',
        components: [
          { name: 'X', type: 'uint256', internalType: 'uint256' },
          { name: 'Y', type: 'uint256', internalType: 'uint256' },
        ],
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'registryCoordinator',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract ISlashingRegistryCoordinator' }],
    stateMutability: 'view',
  },
  { type: 'function', name: 'renounceOwnership', inputs: [], outputs: [], stateMutability: 'nonpayable' },
  {
    type: 'function',
    name: 'respondToTask',
    inputs: [
      {
        name: 'task',
        type: 'tuple',
        internalType: 'struct INewtonProverTaskManager.Task',
        components: [
          { name: 'taskId', type: 'bytes32', internalType: 'bytes32' },
          { name: 'policyId', type: 'bytes32', internalType: 'bytes32' },
          { name: 'policyClient', type: 'address', internalType: 'address' },
          { name: 'nonce', type: 'uint32', internalType: 'uint32' },
          { name: 'taskCreatedBlock', type: 'uint32', internalType: 'uint32' },
          { name: 'quorumThresholdPercentage', type: 'uint32', internalType: 'uint32' },
          {
            name: 'intent',
            type: 'tuple',
            internalType: 'struct NewtonMessage.Intent',
            components: [
              { name: 'from', type: 'address', internalType: 'address' },
              { name: 'to', type: 'address', internalType: 'address' },
              { name: 'value', type: 'uint256', internalType: 'uint256' },
              { name: 'data', type: 'bytes', internalType: 'bytes' },
              { name: 'chainId', type: 'uint256', internalType: 'uint256' },
              { name: 'functionSignature', type: 'bytes', internalType: 'bytes' },
            ],
          },
          { name: 'intentSignature', type: 'bytes', internalType: 'bytes' },
          {
            name: 'policyTaskData',
            type: 'tuple',
            internalType: 'struct NewtonMessage.PolicyTaskData',
            components: [
              { name: 'policyId', type: 'bytes32', internalType: 'bytes32' },
              { name: 'policyAddress', type: 'address', internalType: 'address' },
              { name: 'policy', type: 'bytes', internalType: 'bytes' },
              {
                name: 'policyData',
                type: 'tuple[]',
                internalType: 'struct NewtonMessage.PolicyData[]',
                components: [
                  { name: 'wasmArgs', type: 'bytes', internalType: 'bytes' },
                  { name: 'data', type: 'bytes', internalType: 'bytes' },
                  { name: 'attestation', type: 'bytes', internalType: 'bytes' },
                  { name: 'policyDataAddress', type: 'address', internalType: 'address' },
                  { name: 'expireBlock', type: 'uint32', internalType: 'uint32' },
                ],
              },
            ],
          },
          {
            name: 'policyConfig',
            type: 'tuple',
            internalType: 'struct INewtonPolicy.PolicyConfig',
            components: [
              { name: 'policyParams', type: 'bytes', internalType: 'bytes' },
              { name: 'expireAfter', type: 'uint32', internalType: 'uint32' },
            ],
          },
          { name: 'quorumNumbers', type: 'bytes', internalType: 'bytes' },
        ],
      },
      {
        name: 'taskResponse',
        type: 'tuple',
        internalType: 'struct INewtonProverTaskManager.TaskResponse',
        components: [
          { name: 'taskId', type: 'bytes32', internalType: 'bytes32' },
          { name: 'policyClient', type: 'address', internalType: 'address' },
          { name: 'policyId', type: 'bytes32', internalType: 'bytes32' },
          { name: 'policyAddress', type: 'address', internalType: 'address' },
          {
            name: 'intent',
            type: 'tuple',
            internalType: 'struct NewtonMessage.Intent',
            components: [
              { name: 'from', type: 'address', internalType: 'address' },
              { name: 'to', type: 'address', internalType: 'address' },
              { name: 'value', type: 'uint256', internalType: 'uint256' },
              { name: 'data', type: 'bytes', internalType: 'bytes' },
              { name: 'chainId', type: 'uint256', internalType: 'uint256' },
              { name: 'functionSignature', type: 'bytes', internalType: 'bytes' },
            ],
          },
          { name: 'intentSignature', type: 'bytes', internalType: 'bytes' },
          { name: 'evaluationResult', type: 'bytes', internalType: 'bytes' },
        ],
      },
      {
        name: 'nonSignerStakesAndSignature',
        type: 'tuple',
        internalType: 'struct IBLSSignatureCheckerTypes.NonSignerStakesAndSignature',
        components: [
          { name: 'nonSignerQuorumBitmapIndices', type: 'uint32[]', internalType: 'uint32[]' },
          {
            name: 'nonSignerPubkeys',
            type: 'tuple[]',
            internalType: 'struct BN254.G1Point[]',
            components: [
              { name: 'X', type: 'uint256', internalType: 'uint256' },
              { name: 'Y', type: 'uint256', internalType: 'uint256' },
            ],
          },
          {
            name: 'quorumApks',
            type: 'tuple[]',
            internalType: 'struct BN254.G1Point[]',
            components: [
              { name: 'X', type: 'uint256', internalType: 'uint256' },
              { name: 'Y', type: 'uint256', internalType: 'uint256' },
            ],
          },
          {
            name: 'apkG2',
            type: 'tuple',
            internalType: 'struct BN254.G2Point',
            components: [
              { name: 'X', type: 'uint256[2]', internalType: 'uint256[2]' },
              { name: 'Y', type: 'uint256[2]', internalType: 'uint256[2]' },
            ],
          },
          {
            name: 'sigma',
            type: 'tuple',
            internalType: 'struct BN254.G1Point',
            components: [
              { name: 'X', type: 'uint256', internalType: 'uint256' },
              { name: 'Y', type: 'uint256', internalType: 'uint256' },
            ],
          },
          { name: 'quorumApkIndices', type: 'uint32[]', internalType: 'uint32[]' },
          { name: 'totalStakeIndices', type: 'uint32[]', internalType: 'uint32[]' },
          { name: 'nonSignerStakeIndices', type: 'uint32[][]', internalType: 'uint32[][]' },
        ],
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'serviceManager',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'stakeRegistry',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IStakeRegistry' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'taskHash',
    inputs: [{ name: 'taskId', type: 'bytes32', internalType: 'bytes32' }],
    outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'taskResponseHandler',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'taskResponseHash',
    inputs: [{ name: 'taskId', type: 'bytes32', internalType: 'bytes32' }],
    outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'taskResponseWindowBlock',
    inputs: [],
    outputs: [{ name: '', type: 'uint32', internalType: 'uint32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'transferOwnership',
    inputs: [{ name: 'newOwner', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'trySignatureAndApkVerification',
    inputs: [
      { name: 'msgHash', type: 'bytes32', internalType: 'bytes32' },
      {
        name: 'apk',
        type: 'tuple',
        internalType: 'struct BN254.G1Point',
        components: [
          { name: 'X', type: 'uint256', internalType: 'uint256' },
          { name: 'Y', type: 'uint256', internalType: 'uint256' },
        ],
      },
      {
        name: 'apkG2',
        type: 'tuple',
        internalType: 'struct BN254.G2Point',
        components: [
          { name: 'X', type: 'uint256[2]', internalType: 'uint256[2]' },
          { name: 'Y', type: 'uint256[2]', internalType: 'uint256[2]' },
        ],
      },
      {
        name: 'sigma',
        type: 'tuple',
        internalType: 'struct BN254.G1Point',
        components: [
          { name: 'X', type: 'uint256', internalType: 'uint256' },
          { name: 'Y', type: 'uint256', internalType: 'uint256' },
        ],
      },
    ],
    outputs: [
      { name: 'pairingSuccessful', type: 'bool', internalType: 'bool' },
      { name: 'siganatureIsValid', type: 'bool', internalType: 'bool' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'unpause',
    inputs: [{ name: 'newPausedStatus', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'updateAggregator',
    inputs: [{ name: '_aggregator', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'updateTaskResponseWindowBlock',
    inputs: [{ name: '_taskResponseWindowBlock', type: 'uint32', internalType: 'uint32' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'validateAttestation',
    inputs: [
      {
        name: 'attestation',
        type: 'tuple',
        internalType: 'struct NewtonMessage.Attestation',
        components: [
          { name: 'taskId', type: 'bytes32', internalType: 'bytes32' },
          { name: 'policyId', type: 'bytes32', internalType: 'bytes32' },
          { name: 'policyClient', type: 'address', internalType: 'address' },
          { name: 'expiration', type: 'uint32', internalType: 'uint32' },
          {
            name: 'intent',
            type: 'tuple',
            internalType: 'struct NewtonMessage.Intent',
            components: [
              { name: 'from', type: 'address', internalType: 'address' },
              { name: 'to', type: 'address', internalType: 'address' },
              { name: 'value', type: 'uint256', internalType: 'uint256' },
              { name: 'data', type: 'bytes', internalType: 'bytes' },
              { name: 'chainId', type: 'uint256', internalType: 'uint256' },
              { name: 'functionSignature', type: 'bytes', internalType: 'bytes' },
            ],
          },
          { name: 'intentSignature', type: 'bytes', internalType: 'bytes' },
        ],
      },
    ],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'validateAttestationDirect',
    inputs: [
      {
        name: 'task',
        type: 'tuple',
        internalType: 'struct INewtonProverTaskManager.Task',
        components: [
          { name: 'taskId', type: 'bytes32', internalType: 'bytes32' },
          { name: 'policyId', type: 'bytes32', internalType: 'bytes32' },
          { name: 'policyClient', type: 'address', internalType: 'address' },
          { name: 'nonce', type: 'uint32', internalType: 'uint32' },
          { name: 'taskCreatedBlock', type: 'uint32', internalType: 'uint32' },
          { name: 'quorumThresholdPercentage', type: 'uint32', internalType: 'uint32' },
          {
            name: 'intent',
            type: 'tuple',
            internalType: 'struct NewtonMessage.Intent',
            components: [
              { name: 'from', type: 'address', internalType: 'address' },
              { name: 'to', type: 'address', internalType: 'address' },
              { name: 'value', type: 'uint256', internalType: 'uint256' },
              { name: 'data', type: 'bytes', internalType: 'bytes' },
              { name: 'chainId', type: 'uint256', internalType: 'uint256' },
              { name: 'functionSignature', type: 'bytes', internalType: 'bytes' },
            ],
          },
          { name: 'intentSignature', type: 'bytes', internalType: 'bytes' },
          {
            name: 'policyTaskData',
            type: 'tuple',
            internalType: 'struct NewtonMessage.PolicyTaskData',
            components: [
              { name: 'policyId', type: 'bytes32', internalType: 'bytes32' },
              { name: 'policyAddress', type: 'address', internalType: 'address' },
              { name: 'policy', type: 'bytes', internalType: 'bytes' },
              {
                name: 'policyData',
                type: 'tuple[]',
                internalType: 'struct NewtonMessage.PolicyData[]',
                components: [
                  { name: 'wasmArgs', type: 'bytes', internalType: 'bytes' },
                  { name: 'data', type: 'bytes', internalType: 'bytes' },
                  { name: 'attestation', type: 'bytes', internalType: 'bytes' },
                  { name: 'policyDataAddress', type: 'address', internalType: 'address' },
                  { name: 'expireBlock', type: 'uint32', internalType: 'uint32' },
                ],
              },
            ],
          },
          {
            name: 'policyConfig',
            type: 'tuple',
            internalType: 'struct INewtonPolicy.PolicyConfig',
            components: [
              { name: 'policyParams', type: 'bytes', internalType: 'bytes' },
              { name: 'expireAfter', type: 'uint32', internalType: 'uint32' },
            ],
          },
          { name: 'quorumNumbers', type: 'bytes', internalType: 'bytes' },
        ],
      },
      {
        name: 'taskResponse',
        type: 'tuple',
        internalType: 'struct INewtonProverTaskManager.TaskResponse',
        components: [
          { name: 'taskId', type: 'bytes32', internalType: 'bytes32' },
          { name: 'policyClient', type: 'address', internalType: 'address' },
          { name: 'policyId', type: 'bytes32', internalType: 'bytes32' },
          { name: 'policyAddress', type: 'address', internalType: 'address' },
          {
            name: 'intent',
            type: 'tuple',
            internalType: 'struct NewtonMessage.Intent',
            components: [
              { name: 'from', type: 'address', internalType: 'address' },
              { name: 'to', type: 'address', internalType: 'address' },
              { name: 'value', type: 'uint256', internalType: 'uint256' },
              { name: 'data', type: 'bytes', internalType: 'bytes' },
              { name: 'chainId', type: 'uint256', internalType: 'uint256' },
              { name: 'functionSignature', type: 'bytes', internalType: 'bytes' },
            ],
          },
          { name: 'intentSignature', type: 'bytes', internalType: 'bytes' },
          { name: 'evaluationResult', type: 'bytes', internalType: 'bytes' },
        ],
      },
      {
        name: 'nonSignerStakesAndSignature',
        type: 'tuple',
        internalType: 'struct IBLSSignatureCheckerTypes.NonSignerStakesAndSignature',
        components: [
          { name: 'nonSignerQuorumBitmapIndices', type: 'uint32[]', internalType: 'uint32[]' },
          {
            name: 'nonSignerPubkeys',
            type: 'tuple[]',
            internalType: 'struct BN254.G1Point[]',
            components: [
              { name: 'X', type: 'uint256', internalType: 'uint256' },
              { name: 'Y', type: 'uint256', internalType: 'uint256' },
            ],
          },
          {
            name: 'quorumApks',
            type: 'tuple[]',
            internalType: 'struct BN254.G1Point[]',
            components: [
              { name: 'X', type: 'uint256', internalType: 'uint256' },
              { name: 'Y', type: 'uint256', internalType: 'uint256' },
            ],
          },
          {
            name: 'apkG2',
            type: 'tuple',
            internalType: 'struct BN254.G2Point',
            components: [
              { name: 'X', type: 'uint256[2]', internalType: 'uint256[2]' },
              { name: 'Y', type: 'uint256[2]', internalType: 'uint256[2]' },
            ],
          },
          {
            name: 'sigma',
            type: 'tuple',
            internalType: 'struct BN254.G1Point',
            components: [
              { name: 'X', type: 'uint256', internalType: 'uint256' },
              { name: 'Y', type: 'uint256', internalType: 'uint256' },
            ],
          },
          { name: 'quorumApkIndices', type: 'uint32[]', internalType: 'uint32[]' },
          { name: 'totalStakeIndices', type: 'uint32[]', internalType: 'uint32[]' },
          { name: 'nonSignerStakeIndices', type: 'uint32[][]', internalType: 'uint32[][]' },
        ],
      },
    ],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    name: 'AggregatorUpdated',
    inputs: [
      { name: 'previousAggregator', type: 'address', indexed: true, internalType: 'address' },
      { name: 'newAggregator', type: 'address', indexed: true, internalType: 'address' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'AttestationSpent',
    inputs: [
      { name: 'taskId', type: 'bytes32', indexed: true, internalType: 'bytes32' },
      {
        name: 'attestation',
        type: 'tuple',
        indexed: false,
        internalType: 'struct NewtonMessage.Attestation',
        components: [
          { name: 'taskId', type: 'bytes32', internalType: 'bytes32' },
          { name: 'policyId', type: 'bytes32', internalType: 'bytes32' },
          { name: 'policyClient', type: 'address', internalType: 'address' },
          { name: 'expiration', type: 'uint32', internalType: 'uint32' },
          {
            name: 'intent',
            type: 'tuple',
            internalType: 'struct NewtonMessage.Intent',
            components: [
              { name: 'from', type: 'address', internalType: 'address' },
              { name: 'to', type: 'address', internalType: 'address' },
              { name: 'value', type: 'uint256', internalType: 'uint256' },
              { name: 'data', type: 'bytes', internalType: 'bytes' },
              { name: 'chainId', type: 'uint256', internalType: 'uint256' },
              { name: 'functionSignature', type: 'bytes', internalType: 'bytes' },
            ],
          },
          { name: 'intentSignature', type: 'bytes', internalType: 'bytes' },
        ],
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Initialized',
    inputs: [{ name: 'version', type: 'uint8', indexed: false, internalType: 'uint8' }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'NewTaskCreated',
    inputs: [
      { name: 'taskId', type: 'bytes32', indexed: true, internalType: 'bytes32' },
      {
        name: 'task',
        type: 'tuple',
        indexed: false,
        internalType: 'struct INewtonProverTaskManager.Task',
        components: [
          { name: 'taskId', type: 'bytes32', internalType: 'bytes32' },
          { name: 'policyId', type: 'bytes32', internalType: 'bytes32' },
          { name: 'policyClient', type: 'address', internalType: 'address' },
          { name: 'nonce', type: 'uint32', internalType: 'uint32' },
          { name: 'taskCreatedBlock', type: 'uint32', internalType: 'uint32' },
          { name: 'quorumThresholdPercentage', type: 'uint32', internalType: 'uint32' },
          {
            name: 'intent',
            type: 'tuple',
            internalType: 'struct NewtonMessage.Intent',
            components: [
              { name: 'from', type: 'address', internalType: 'address' },
              { name: 'to', type: 'address', internalType: 'address' },
              { name: 'value', type: 'uint256', internalType: 'uint256' },
              { name: 'data', type: 'bytes', internalType: 'bytes' },
              { name: 'chainId', type: 'uint256', internalType: 'uint256' },
              { name: 'functionSignature', type: 'bytes', internalType: 'bytes' },
            ],
          },
          { name: 'intentSignature', type: 'bytes', internalType: 'bytes' },
          {
            name: 'policyTaskData',
            type: 'tuple',
            internalType: 'struct NewtonMessage.PolicyTaskData',
            components: [
              { name: 'policyId', type: 'bytes32', internalType: 'bytes32' },
              { name: 'policyAddress', type: 'address', internalType: 'address' },
              { name: 'policy', type: 'bytes', internalType: 'bytes' },
              {
                name: 'policyData',
                type: 'tuple[]',
                internalType: 'struct NewtonMessage.PolicyData[]',
                components: [
                  { name: 'wasmArgs', type: 'bytes', internalType: 'bytes' },
                  { name: 'data', type: 'bytes', internalType: 'bytes' },
                  { name: 'attestation', type: 'bytes', internalType: 'bytes' },
                  { name: 'policyDataAddress', type: 'address', internalType: 'address' },
                  { name: 'expireBlock', type: 'uint32', internalType: 'uint32' },
                ],
              },
            ],
          },
          {
            name: 'policyConfig',
            type: 'tuple',
            internalType: 'struct INewtonPolicy.PolicyConfig',
            components: [
              { name: 'policyParams', type: 'bytes', internalType: 'bytes' },
              { name: 'expireAfter', type: 'uint32', internalType: 'uint32' },
            ],
          },
          { name: 'quorumNumbers', type: 'bytes', internalType: 'bytes' },
        ],
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'OwnershipTransferred',
    inputs: [
      { name: 'previousOwner', type: 'address', indexed: true, internalType: 'address' },
      { name: 'newOwner', type: 'address', indexed: true, internalType: 'address' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Paused',
    inputs: [
      { name: 'account', type: 'address', indexed: true, internalType: 'address' },
      { name: 'newPausedStatus', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'TaskChallengedSuccessfully',
    inputs: [
      { name: 'taskId', type: 'bytes32', indexed: true, internalType: 'bytes32' },
      { name: 'challenger', type: 'address', indexed: true, internalType: 'address' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'TaskChallengedUnsuccessfully',
    inputs: [
      { name: 'taskId', type: 'bytes32', indexed: true, internalType: 'bytes32' },
      { name: 'challenger', type: 'address', indexed: true, internalType: 'address' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'TaskResponded',
    inputs: [
      {
        name: 'taskResponse',
        type: 'tuple',
        indexed: false,
        internalType: 'struct INewtonProverTaskManager.TaskResponse',
        components: [
          { name: 'taskId', type: 'bytes32', internalType: 'bytes32' },
          { name: 'policyClient', type: 'address', internalType: 'address' },
          { name: 'policyId', type: 'bytes32', internalType: 'bytes32' },
          { name: 'policyAddress', type: 'address', internalType: 'address' },
          {
            name: 'intent',
            type: 'tuple',
            internalType: 'struct NewtonMessage.Intent',
            components: [
              { name: 'from', type: 'address', internalType: 'address' },
              { name: 'to', type: 'address', internalType: 'address' },
              { name: 'value', type: 'uint256', internalType: 'uint256' },
              { name: 'data', type: 'bytes', internalType: 'bytes' },
              { name: 'chainId', type: 'uint256', internalType: 'uint256' },
              { name: 'functionSignature', type: 'bytes', internalType: 'bytes' },
            ],
          },
          { name: 'intentSignature', type: 'bytes', internalType: 'bytes' },
          { name: 'evaluationResult', type: 'bytes', internalType: 'bytes' },
        ],
      },
      {
        name: 'responseCertificate',
        type: 'tuple',
        indexed: false,
        internalType: 'struct INewtonProverTaskManager.ResponseCertificate',
        components: [
          { name: 'referenceBlock', type: 'uint32', internalType: 'uint32' },
          { name: 'responseExpireBlock', type: 'uint32', internalType: 'uint32' },
          { name: 'hashOfNonSigners', type: 'bytes32', internalType: 'bytes32' },
          {
            name: 'nonSignerStakesAndSignature',
            type: 'tuple',
            internalType: 'struct IBLSSignatureCheckerTypes.NonSignerStakesAndSignature',
            components: [
              { name: 'nonSignerQuorumBitmapIndices', type: 'uint32[]', internalType: 'uint32[]' },
              {
                name: 'nonSignerPubkeys',
                type: 'tuple[]',
                internalType: 'struct BN254.G1Point[]',
                components: [
                  { name: 'X', type: 'uint256', internalType: 'uint256' },
                  { name: 'Y', type: 'uint256', internalType: 'uint256' },
                ],
              },
              {
                name: 'quorumApks',
                type: 'tuple[]',
                internalType: 'struct BN254.G1Point[]',
                components: [
                  { name: 'X', type: 'uint256', internalType: 'uint256' },
                  { name: 'Y', type: 'uint256', internalType: 'uint256' },
                ],
              },
              {
                name: 'apkG2',
                type: 'tuple',
                internalType: 'struct BN254.G2Point',
                components: [
                  { name: 'X', type: 'uint256[2]', internalType: 'uint256[2]' },
                  { name: 'Y', type: 'uint256[2]', internalType: 'uint256[2]' },
                ],
              },
              {
                name: 'sigma',
                type: 'tuple',
                internalType: 'struct BN254.G1Point',
                components: [
                  { name: 'X', type: 'uint256', internalType: 'uint256' },
                  { name: 'Y', type: 'uint256', internalType: 'uint256' },
                ],
              },
              { name: 'quorumApkIndices', type: 'uint32[]', internalType: 'uint32[]' },
              { name: 'totalStakeIndices', type: 'uint32[]', internalType: 'uint32[]' },
              { name: 'nonSignerStakeIndices', type: 'uint32[][]', internalType: 'uint32[][]' },
            ],
          },
        ],
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Unpaused',
    inputs: [
      { name: 'account', type: 'address', indexed: true, internalType: 'address' },
      { name: 'newPausedStatus', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  { type: 'error', name: 'BitmapValueTooLarge', inputs: [] },
  { type: 'error', name: 'BytesArrayLengthTooLong', inputs: [] },
  { type: 'error', name: 'BytesArrayNotOrdered', inputs: [] },
  { type: 'error', name: 'CurrentlyPaused', inputs: [] },
  { type: 'error', name: 'ECAddFailed', inputs: [] },
  { type: 'error', name: 'ECMulFailed', inputs: [] },
  { type: 'error', name: 'ExpModFailed', inputs: [] },
  { type: 'error', name: 'InputAddressZero', inputs: [] },
  { type: 'error', name: 'InputArrayLengthMismatch', inputs: [] },
  { type: 'error', name: 'InputEmptyQuorumNumbers', inputs: [] },
  { type: 'error', name: 'InputNonSignerLengthMismatch', inputs: [] },
  { type: 'error', name: 'InvalidAggregatorAddress', inputs: [] },
  { type: 'error', name: 'InvalidBLSPairingKey', inputs: [] },
  { type: 'error', name: 'InvalidBLSSignature', inputs: [] },
  { type: 'error', name: 'InvalidNewPausedStatus', inputs: [] },
  { type: 'error', name: 'InvalidQuorumApkHash', inputs: [] },
  { type: 'error', name: 'InvalidReferenceBlocknumber', inputs: [] },
  { type: 'error', name: 'NonSignerPubkeysNotSorted', inputs: [] },
  { type: 'error', name: 'OnlyAggregator', inputs: [] },
  { type: 'error', name: 'OnlyPauser', inputs: [] },
  { type: 'error', name: 'OnlyRegistryCoordinatorOwner', inputs: [] },
  { type: 'error', name: 'OnlyTaskGenerator', inputs: [] },
  { type: 'error', name: 'OnlyUnpauser', inputs: [] },
  { type: 'error', name: 'OperatorNotRegistered', inputs: [] },
  { type: 'error', name: 'ScalarTooLarge', inputs: [] },
  { type: 'error', name: 'TaskAlreadyResponded', inputs: [] },
  {
    type: 'error',
    name: 'TaskMismatch',
    inputs: [
      { name: 'expected', type: 'bytes32', internalType: 'bytes32' },
      { name: 'actual', type: 'bytes32', internalType: 'bytes32' },
    ],
  },
];

export type TaskRespondedLog = Log & {
  args: {
    taskResponse: {
      taskId: Hex;
      policyClient: Address;
      policyId: Hex;
      policyAddress: Address;
      intent: {
        from: Address;
        to: Address;
        value: string; // string representation of big int
        data: Hex;
        chainId: string; // string representation of big int
        functionSignature: Hex;
      };
      intentSignature: Hex;
      evaluationResult: Hex;
    };
    responseCertificate: {
      taskResponsedBlock: string;
      responseExpireBlock: string;
      hashOfNonSigners: Hex;
    };
  };
};
