import type { Address, Hex, Log } from 'viem';

export const AttestationValidatorAbi = [
  {
    type: 'constructor',
    inputs: [
      { name: '_taskManager', type: 'address', internalType: 'address' },
      { name: '_operatorRegistry', type: 'address', internalType: 'address' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'attestationExpirations',
    inputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    outputs: [{ name: '', type: 'uint32', internalType: 'uint32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'attestationHash',
    inputs: [{ name: 'taskId', type: 'bytes32', internalType: 'bytes32' }],
    outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'attestations',
    inputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'createAttestationHash',
    inputs: [
      { name: 'taskId', type: 'bytes32', internalType: 'bytes32' },
      { name: 'policyId', type: 'bytes32', internalType: 'bytes32' },
      { name: 'policyClient', type: 'address', internalType: 'address' },
      {
        name: 'intent',
        type: 'tuple',
        internalType: 'struct NewtonMessage.Intent',
        components: [
          { name: 'from', type: 'address', internalType: 'address' },
          { name: 'to', type: 'address', internalType: 'address' },
          { name: 'value', type: 'uint256', internalType: 'uint256' },
          { name: 'data', type: 'bytes', internalType: 'bytes' },
          { name: 'chainId', type: 'uint256', internalType: 'uint256' },
          { name: 'functionSignature', type: 'bytes', internalType: 'bytes' },
        ],
      },
      { name: 'intentSignature', type: 'bytes', internalType: 'bytes' },
      { name: 'expiration', type: 'uint32', internalType: 'uint32' },
    ],
    outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'directlyVerifiedAttestations',
    inputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'initialize',
    inputs: [{ name: '_owner', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'invalidateAttestation',
    inputs: [{ name: 'taskId', type: 'bytes32', internalType: 'bytes32' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'isAttestationValid',
    inputs: [
      {
        name: 'attestation',
        type: 'tuple',
        internalType: 'struct NewtonMessage.Attestation',
        components: [
          { name: 'taskId', type: 'bytes32', internalType: 'bytes32' },
          { name: 'policyId', type: 'bytes32', internalType: 'bytes32' },
          { name: 'policyClient', type: 'address', internalType: 'address' },
          { name: 'expiration', type: 'uint32', internalType: 'uint32' },
          {
            name: 'intent',
            type: 'tuple',
            internalType: 'struct NewtonMessage.Intent',
            components: [
              { name: 'from', type: 'address', internalType: 'address' },
              { name: 'to', type: 'address', internalType: 'address' },
              { name: 'value', type: 'uint256', internalType: 'uint256' },
              { name: 'data', type: 'bytes', internalType: 'bytes' },
              { name: 'chainId', type: 'uint256', internalType: 'uint256' },
              { name: 'functionSignature', type: 'bytes', internalType: 'bytes' },
            ],
          },
          { name: 'intentSignature', type: 'bytes', internalType: 'bytes' },
        ],
      },
    ],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'isDirectlyVerified',
    inputs: [{ name: 'taskId', type: 'bytes32', internalType: 'bytes32' }],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'markDirectlyVerified',
    inputs: [{ name: 'taskId', type: 'bytes32', internalType: 'bytes32' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'operatorRegistry',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'owner',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  { type: 'function', name: 'renounceOwnership', inputs: [], outputs: [], stateMutability: 'nonpayable' },
  {
    type: 'function',
    name: 'taskManager',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'transferOwnership',
    inputs: [{ name: 'newOwner', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'validateAttestation',
    inputs: [
      {
        name: 'attestation',
        type: 'tuple',
        internalType: 'struct NewtonMessage.Attestation',
        components: [
          { name: 'taskId', type: 'bytes32', internalType: 'bytes32' },
          { name: 'policyId', type: 'bytes32', internalType: 'bytes32' },
          { name: 'policyClient', type: 'address', internalType: 'address' },
          { name: 'expiration', type: 'uint32', internalType: 'uint32' },
          {
            name: 'intent',
            type: 'tuple',
            internalType: 'struct NewtonMessage.Intent',
            components: [
              { name: 'from', type: 'address', internalType: 'address' },
              { name: 'to', type: 'address', internalType: 'address' },
              { name: 'value', type: 'uint256', internalType: 'uint256' },
              { name: 'data', type: 'bytes', internalType: 'bytes' },
              { name: 'chainId', type: 'uint256', internalType: 'uint256' },
              { name: 'functionSignature', type: 'bytes', internalType: 'bytes' },
            ],
          },
          { name: 'intentSignature', type: 'bytes', internalType: 'bytes' },
        ],
      },
    ],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'validateAttestationDirect',
    inputs: [
      {
        name: 'task',
        type: 'tuple',
        internalType: 'struct INewtonProverTaskManager.Task',
        components: [
          { name: 'taskId', type: 'bytes32', internalType: 'bytes32' },
          { name: 'policyId', type: 'bytes32', internalType: 'bytes32' },
          { name: 'policyClient', type: 'address', internalType: 'address' },
          { name: 'nonce', type: 'uint32', internalType: 'uint32' },
          { name: 'taskCreatedBlock', type: 'uint32', internalType: 'uint32' },
          { name: 'quorumThresholdPercentage', type: 'uint32', internalType: 'uint32' },
          {
            name: 'intent',
            type: 'tuple',
            internalType: 'struct NewtonMessage.Intent',
            components: [
              { name: 'from', type: 'address', internalType: 'address' },
              { name: 'to', type: 'address', internalType: 'address' },
              { name: 'value', type: 'uint256', internalType: 'uint256' },
              { name: 'data', type: 'bytes', internalType: 'bytes' },
              { name: 'chainId', type: 'uint256', internalType: 'uint256' },
              { name: 'functionSignature', type: 'bytes', internalType: 'bytes' },
            ],
          },
          { name: 'intentSignature', type: 'bytes', internalType: 'bytes' },
          {
            name: 'policyTaskData',
            type: 'tuple',
            internalType: 'struct NewtonMessage.PolicyTaskData',
            components: [
              { name: 'policyId', type: 'bytes32', internalType: 'bytes32' },
              { name: 'policyAddress', type: 'address', internalType: 'address' },
              { name: 'policy', type: 'bytes', internalType: 'bytes' },
              {
                name: 'policyData',
                type: 'tuple[]',
                internalType: 'struct NewtonMessage.PolicyData[]',
                components: [
                  { name: 'wasmArgs', type: 'bytes', internalType: 'bytes' },
                  { name: 'data', type: 'bytes', internalType: 'bytes' },
                  { name: 'attestation', type: 'bytes', internalType: 'bytes' },
                  { name: 'policyDataAddress', type: 'address', internalType: 'address' },
                  { name: 'expireBlock', type: 'uint32', internalType: 'uint32' },
                ],
              },
            ],
          },
          {
            name: 'policyConfig',
            type: 'tuple',
            internalType: 'struct INewtonPolicy.PolicyConfig',
            components: [
              { name: 'policyParams', type: 'bytes', internalType: 'bytes' },
              { name: 'expireAfter', type: 'uint32', internalType: 'uint32' },
            ],
          },
          { name: 'quorumNumbers', type: 'bytes', internalType: 'bytes' },
        ],
      },
      {
        name: 'taskResponse',
        type: 'tuple',
        internalType: 'struct INewtonProverTaskManager.TaskResponse',
        components: [
          { name: 'taskId', type: 'bytes32', internalType: 'bytes32' },
          { name: 'policyClient', type: 'address', internalType: 'address' },
          { name: 'policyId', type: 'bytes32', internalType: 'bytes32' },
          { name: 'policyAddress', type: 'address', internalType: 'address' },
          {
            name: 'intent',
            type: 'tuple',
            internalType: 'struct NewtonMessage.Intent',
            components: [
              { name: 'from', type: 'address', internalType: 'address' },
              { name: 'to', type: 'address', internalType: 'address' },
              { name: 'value', type: 'uint256', internalType: 'uint256' },
              { name: 'data', type: 'bytes', internalType: 'bytes' },
              { name: 'chainId', type: 'uint256', internalType: 'uint256' },
              { name: 'functionSignature', type: 'bytes', internalType: 'bytes' },
            ],
          },
          { name: 'intentSignature', type: 'bytes', internalType: 'bytes' },
          { name: 'evaluationResult', type: 'bytes', internalType: 'bytes' },
        ],
      },
      {
        name: 'nonSignerStakesAndSignature',
        type: 'tuple',
        internalType: 'struct IBLSSignatureCheckerTypes.NonSignerStakesAndSignature',
        components: [
          { name: 'nonSignerQuorumBitmapIndices', type: 'uint32[]', internalType: 'uint32[]' },
          {
            name: 'nonSignerPubkeys',
            type: 'tuple[]',
            internalType: 'struct BN254.G1Point[]',
            components: [
              { name: 'X', type: 'uint256', internalType: 'uint256' },
              { name: 'Y', type: 'uint256', internalType: 'uint256' },
            ],
          },
          {
            name: 'quorumApks',
            type: 'tuple[]',
            internalType: 'struct BN254.G1Point[]',
            components: [
              { name: 'X', type: 'uint256', internalType: 'uint256' },
              { name: 'Y', type: 'uint256', internalType: 'uint256' },
            ],
          },
          {
            name: 'apkG2',
            type: 'tuple',
            internalType: 'struct BN254.G2Point',
            components: [
              { name: 'X', type: 'uint256[2]', internalType: 'uint256[2]' },
              { name: 'Y', type: 'uint256[2]', internalType: 'uint256[2]' },
            ],
          },
          {
            name: 'sigma',
            type: 'tuple',
            internalType: 'struct BN254.G1Point',
            components: [
              { name: 'X', type: 'uint256', internalType: 'uint256' },
              { name: 'Y', type: 'uint256', internalType: 'uint256' },
            ],
          },
          { name: 'quorumApkIndices', type: 'uint32[]', internalType: 'uint32[]' },
          { name: 'totalStakeIndices', type: 'uint32[]', internalType: 'uint32[]' },
          { name: 'nonSignerStakeIndices', type: 'uint32[][]', internalType: 'uint32[][]' },
        ],
      },
      {
        name: 'checkSignatures',
        type: 'function',
        internalType:
          'function (bytes32,bytes,uint32,struct IBLSSignatureCheckerTypes.NonSignerStakesAndSignature) view external returns (struct IBLSSignatureCheckerTypes.QuorumStakeTotals,bytes32)',
      },
    ],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    name: 'Initialized',
    inputs: [{ name: 'version', type: 'uint8', indexed: false, internalType: 'uint8' }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'OwnershipTransferred',
    inputs: [
      { name: 'previousOwner', type: 'address', indexed: true, internalType: 'address' },
      { name: 'newOwner', type: 'address', indexed: true, internalType: 'address' },
    ],
    anonymous: false,
  },
  { type: 'error', name: 'AttestationAlreadySpent', inputs: [] },
  { type: 'error', name: 'AttestationExpired', inputs: [] },
  { type: 'error', name: 'AttestationHashMismatch', inputs: [] },
  { type: 'error', name: 'OnlyTaskManager', inputs: [] },
  { type: 'error', name: 'PolicyNotVerified', inputs: [] },
  {
    type: 'error',
    name: 'TaskMismatch',
    inputs: [
      { name: 'expected', type: 'bytes32', internalType: 'bytes32' },
      { name: 'actual', type: 'bytes32', internalType: 'bytes32' },
    ],
  },
];

export const NewtonProverTaskManagerAbi = [
  {
    inputs: [
      { internalType: 'contract OperatorRegistry', name: '_operatorRegistry', type: 'address' },
      { internalType: 'contract IPauserRegistry', name: '_pauserRegistry', type: 'address' },
      { internalType: 'string', name: '_version', type: 'string' },
    ],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  { inputs: [], name: 'BitmapValueTooLarge', type: 'error' },
  { inputs: [], name: 'BytesArrayLengthTooLong', type: 'error' },
  { inputs: [], name: 'BytesArrayNotOrdered', type: 'error' },
  { inputs: [], name: 'CurrentlyPaused', type: 'error' },
  { inputs: [], name: 'ECAddFailed', type: 'error' },
  { inputs: [], name: 'ECMulFailed', type: 'error' },
  { inputs: [], name: 'ExpModFailed', type: 'error' },
  { inputs: [], name: 'InputAddressZero', type: 'error' },
  { inputs: [], name: 'InputArrayLengthMismatch', type: 'error' },
  { inputs: [], name: 'InputEmptyQuorumNumbers', type: 'error' },
  { inputs: [], name: 'InputNonSignerLengthMismatch', type: 'error' },
  { inputs: [], name: 'InvalidBLSPairingKey', type: 'error' },
  { inputs: [], name: 'InvalidBLSSignature', type: 'error' },
  { inputs: [], name: 'InvalidNewPausedStatus', type: 'error' },
  { inputs: [], name: 'InvalidQuorumApkHash', type: 'error' },
  { inputs: [], name: 'InvalidReferenceBlocknumber', type: 'error' },
  { inputs: [], name: 'InvalidShortString', type: 'error' },
  { inputs: [], name: 'NonSignerPubkeysNotSorted', type: 'error' },
  { inputs: [], name: 'OnlyPauser', type: 'error' },
  { inputs: [], name: 'OnlyRegistryCoordinatorOwner', type: 'error' },
  { inputs: [], name: 'OnlyTaskGenerator', type: 'error' },
  { inputs: [], name: 'OnlyUnpauser', type: 'error' },
  { inputs: [], name: 'OperatorNotRegistered', type: 'error' },
  { inputs: [], name: 'ScalarTooLarge', type: 'error' },
  { inputs: [{ internalType: 'string', name: 'str', type: 'string' }], name: 'StringTooLong', type: 'error' },
  { inputs: [], name: 'TaskAlreadyResponded', type: 'error' },
  {
    inputs: [
      { internalType: 'bytes32', name: 'expected', type: 'bytes32' },
      { internalType: 'bytes32', name: 'actual', type: 'bytes32' },
    ],
    name: 'TaskMismatch',
    type: 'error',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'previousAggregator', type: 'address' },
      { indexed: true, internalType: 'address', name: 'newAggregator', type: 'address' },
    ],
    name: 'AggregatorUpdated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'bytes32', name: 'taskId', type: 'bytes32' },
      {
        components: [
          { internalType: 'bytes32', name: 'taskId', type: 'bytes32' },
          { internalType: 'bytes32', name: 'policyId', type: 'bytes32' },
          { internalType: 'address', name: 'policyClient', type: 'address' },
          { internalType: 'uint32', name: 'expiration', type: 'uint32' },
          {
            components: [
              { internalType: 'address', name: 'from', type: 'address' },
              { internalType: 'address', name: 'to', type: 'address' },
              { internalType: 'uint256', name: 'value', type: 'uint256' },
              { internalType: 'bytes', name: 'data', type: 'bytes' },
              { internalType: 'uint256', name: 'chainId', type: 'uint256' },
              { internalType: 'bytes', name: 'functionSignature', type: 'bytes' },
            ],
            internalType: 'struct NewtonMessage.Intent',
            name: 'intent',
            type: 'tuple',
          },
          { internalType: 'bytes', name: 'intentSignature', type: 'bytes' },
        ],
        indexed: false,
        internalType: 'struct NewtonMessage.Attestation',
        name: 'attestation',
        type: 'tuple',
      },
    ],
    name: 'AttestationSpent',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: 'uint8', name: 'version', type: 'uint8' }],
    name: 'Initialized',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'bytes32', name: 'taskId', type: 'bytes32' },
      {
        components: [
          { internalType: 'bytes32', name: 'taskId', type: 'bytes32' },
          { internalType: 'bytes32', name: 'policyId', type: 'bytes32' },
          { internalType: 'address', name: 'policyClient', type: 'address' },
          { internalType: 'uint32', name: 'nonce', type: 'uint32' },
          { internalType: 'uint32', name: 'taskCreatedBlock', type: 'uint32' },
          { internalType: 'uint32', name: 'quorumThresholdPercentage', type: 'uint32' },
          {
            components: [
              { internalType: 'address', name: 'from', type: 'address' },
              { internalType: 'address', name: 'to', type: 'address' },
              { internalType: 'uint256', name: 'value', type: 'uint256' },
              { internalType: 'bytes', name: 'data', type: 'bytes' },
              { internalType: 'uint256', name: 'chainId', type: 'uint256' },
              { internalType: 'bytes', name: 'functionSignature', type: 'bytes' },
            ],
            internalType: 'struct NewtonMessage.Intent',
            name: 'intent',
            type: 'tuple',
          },
          { internalType: 'bytes', name: 'intentSignature', type: 'bytes' },
          {
            components: [
              { internalType: 'bytes32', name: 'policyId', type: 'bytes32' },
              { internalType: 'address', name: 'policyAddress', type: 'address' },
              { internalType: 'bytes', name: 'policy', type: 'bytes' },
              {
                components: [
                  { internalType: 'bytes', name: 'wasmArgs', type: 'bytes' },
                  { internalType: 'bytes', name: 'data', type: 'bytes' },
                  { internalType: 'bytes', name: 'attestation', type: 'bytes' },
                  { internalType: 'address', name: 'policyDataAddress', type: 'address' },
                  { internalType: 'uint32', name: 'expireBlock', type: 'uint32' },
                ],
                internalType: 'struct NewtonMessage.PolicyData[]',
                name: 'policyData',
                type: 'tuple[]',
              },
            ],
            internalType: 'struct NewtonMessage.PolicyTaskData',
            name: 'policyTaskData',
            type: 'tuple',
          },
          {
            components: [
              { internalType: 'bytes', name: 'policyParams', type: 'bytes' },
              { internalType: 'uint32', name: 'expireAfter', type: 'uint32' },
            ],
            internalType: 'struct INewtonPolicy.PolicyConfig',
            name: 'policyConfig',
            type: 'tuple',
          },
          { internalType: 'bytes', name: 'quorumNumbers', type: 'bytes' },
        ],
        indexed: false,
        internalType: 'struct INewtonProverTaskManager.Task',
        name: 'task',
        type: 'tuple',
      },
    ],
    name: 'NewTaskCreated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'previousOwner', type: 'address' },
      { indexed: true, internalType: 'address', name: 'newOwner', type: 'address' },
    ],
    name: 'OwnershipTransferred',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'account', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'newPausedStatus', type: 'uint256' },
    ],
    name: 'Paused',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'bytes32', name: 'taskId', type: 'bytes32' },
      { indexed: true, internalType: 'address', name: 'challenger', type: 'address' },
    ],
    name: 'TaskChallengedSuccessfully',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'bytes32', name: 'taskId', type: 'bytes32' },
      { indexed: true, internalType: 'address', name: 'challenger', type: 'address' },
    ],
    name: 'TaskChallengedUnsuccessfully',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        components: [
          { internalType: 'bytes32', name: 'taskId', type: 'bytes32' },
          { internalType: 'address', name: 'policyClient', type: 'address' },
          { internalType: 'bytes32', name: 'policyId', type: 'bytes32' },
          { internalType: 'address', name: 'policyAddress', type: 'address' },
          {
            components: [
              { internalType: 'address', name: 'from', type: 'address' },
              { internalType: 'address', name: 'to', type: 'address' },
              { internalType: 'uint256', name: 'value', type: 'uint256' },
              { internalType: 'bytes', name: 'data', type: 'bytes' },
              { internalType: 'uint256', name: 'chainId', type: 'uint256' },
              { internalType: 'bytes', name: 'functionSignature', type: 'bytes' },
            ],
            internalType: 'struct NewtonMessage.Intent',
            name: 'intent',
            type: 'tuple',
          },
          { internalType: 'bytes', name: 'intentSignature', type: 'bytes' },
          { internalType: 'bytes', name: 'evaluationResult', type: 'bytes' },
        ],
        indexed: false,
        internalType: 'struct INewtonProverTaskManager.TaskResponse',
        name: 'taskResponse',
        type: 'tuple',
      },
      {
        components: [
          { internalType: 'uint32', name: 'referenceBlock', type: 'uint32' },
          { internalType: 'uint32', name: 'responseExpireBlock', type: 'uint32' },
          { internalType: 'bytes32', name: 'hashOfNonSigners', type: 'bytes32' },
          { internalType: 'bytes', name: 'signatureData', type: 'bytes' },
        ],
        indexed: false,
        internalType: 'struct INewtonProverTaskManager.ResponseCertificate',
        name: 'responseCertificate',
        type: 'tuple',
      },
    ],
    name: 'TaskResponded',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'account', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'newPausedStatus', type: 'uint256' },
    ],
    name: 'Unpaused',
    type: 'event',
  },
  {
    inputs: [],
    name: 'aggregator',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    name: 'allTaskHashes',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    name: 'allTaskResponses',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'attestationValidator',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'blsApkRegistry',
    outputs: [{ internalType: 'contract IBLSApkRegistry', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'certificateVerifier',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'bytes32', name: 'taskId', type: 'bytes32' },
          { internalType: 'bytes32', name: 'policyId', type: 'bytes32' },
          { internalType: 'address', name: 'policyClient', type: 'address' },
          { internalType: 'uint32', name: 'nonce', type: 'uint32' },
          { internalType: 'uint32', name: 'taskCreatedBlock', type: 'uint32' },
          { internalType: 'uint32', name: 'quorumThresholdPercentage', type: 'uint32' },
          {
            components: [
              { internalType: 'address', name: 'from', type: 'address' },
              { internalType: 'address', name: 'to', type: 'address' },
              { internalType: 'uint256', name: 'value', type: 'uint256' },
              { internalType: 'bytes', name: 'data', type: 'bytes' },
              { internalType: 'uint256', name: 'chainId', type: 'uint256' },
              { internalType: 'bytes', name: 'functionSignature', type: 'bytes' },
            ],
            internalType: 'struct NewtonMessage.Intent',
            name: 'intent',
            type: 'tuple',
          },
          { internalType: 'bytes', name: 'intentSignature', type: 'bytes' },
          {
            components: [
              { internalType: 'bytes32', name: 'policyId', type: 'bytes32' },
              { internalType: 'address', name: 'policyAddress', type: 'address' },
              { internalType: 'bytes', name: 'policy', type: 'bytes' },
              {
                components: [
                  { internalType: 'bytes', name: 'wasmArgs', type: 'bytes' },
                  { internalType: 'bytes', name: 'data', type: 'bytes' },
                  { internalType: 'bytes', name: 'attestation', type: 'bytes' },
                  { internalType: 'address', name: 'policyDataAddress', type: 'address' },
                  { internalType: 'uint32', name: 'expireBlock', type: 'uint32' },
                ],
                internalType: 'struct NewtonMessage.PolicyData[]',
                name: 'policyData',
                type: 'tuple[]',
              },
            ],
            internalType: 'struct NewtonMessage.PolicyTaskData',
            name: 'policyTaskData',
            type: 'tuple',
          },
          {
            components: [
              { internalType: 'bytes', name: 'policyParams', type: 'bytes' },
              { internalType: 'uint32', name: 'expireAfter', type: 'uint32' },
            ],
            internalType: 'struct INewtonPolicy.PolicyConfig',
            name: 'policyConfig',
            type: 'tuple',
          },
          { internalType: 'bytes', name: 'quorumNumbers', type: 'bytes' },
        ],
        internalType: 'struct INewtonProverTaskManager.Task',
        name: 'task',
        type: 'tuple',
      },
      {
        components: [
          { internalType: 'bytes32', name: 'taskId', type: 'bytes32' },
          { internalType: 'address', name: 'policyClient', type: 'address' },
          { internalType: 'bytes32', name: 'policyId', type: 'bytes32' },
          { internalType: 'address', name: 'policyAddress', type: 'address' },
          {
            components: [
              { internalType: 'address', name: 'from', type: 'address' },
              { internalType: 'address', name: 'to', type: 'address' },
              { internalType: 'uint256', name: 'value', type: 'uint256' },
              { internalType: 'bytes', name: 'data', type: 'bytes' },
              { internalType: 'uint256', name: 'chainId', type: 'uint256' },
              { internalType: 'bytes', name: 'functionSignature', type: 'bytes' },
            ],
            internalType: 'struct NewtonMessage.Intent',
            name: 'intent',
            type: 'tuple',
          },
          { internalType: 'bytes', name: 'intentSignature', type: 'bytes' },
          { internalType: 'bytes', name: 'evaluationResult', type: 'bytes' },
        ],
        internalType: 'struct INewtonProverTaskManager.TaskResponse',
        name: 'taskResponse',
        type: 'tuple',
      },
      {
        components: [
          { internalType: 'uint32[]', name: 'nonSignerQuorumBitmapIndices', type: 'uint32[]' },
          {
            components: [
              { internalType: 'uint256', name: 'X', type: 'uint256' },
              { internalType: 'uint256', name: 'Y', type: 'uint256' },
            ],
            internalType: 'struct BN254.G1Point[]',
            name: 'nonSignerPubkeys',
            type: 'tuple[]',
          },
          {
            components: [
              { internalType: 'uint256', name: 'X', type: 'uint256' },
              { internalType: 'uint256', name: 'Y', type: 'uint256' },
            ],
            internalType: 'struct BN254.G1Point[]',
            name: 'quorumApks',
            type: 'tuple[]',
          },
          {
            components: [
              { internalType: 'uint256[2]', name: 'X', type: 'uint256[2]' },
              { internalType: 'uint256[2]', name: 'Y', type: 'uint256[2]' },
            ],
            internalType: 'struct BN254.G2Point',
            name: 'apkG2',
            type: 'tuple',
          },
          {
            components: [
              { internalType: 'uint256', name: 'X', type: 'uint256' },
              { internalType: 'uint256', name: 'Y', type: 'uint256' },
            ],
            internalType: 'struct BN254.G1Point',
            name: 'sigma',
            type: 'tuple',
          },
          { internalType: 'uint32[]', name: 'quorumApkIndices', type: 'uint32[]' },
          { internalType: 'uint32[]', name: 'totalStakeIndices', type: 'uint32[]' },
          { internalType: 'uint32[][]', name: 'nonSignerStakeIndices', type: 'uint32[][]' },
        ],
        internalType: 'struct IBLSSignatureCheckerTypes.NonSignerStakesAndSignature',
        name: 'nonSignerStakesAndSignature',
        type: 'tuple',
      },
    ],
    name: 'challengeDirectlyVerifiedAttestation',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'challengeVerifier',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes32', name: 'msgHash', type: 'bytes32' },
      { internalType: 'bytes', name: 'quorumNumbers', type: 'bytes' },
      { internalType: 'uint32', name: 'referenceBlockNumber', type: 'uint32' },
      {
        components: [
          { internalType: 'uint32[]', name: 'nonSignerQuorumBitmapIndices', type: 'uint32[]' },
          {
            components: [
              { internalType: 'uint256', name: 'X', type: 'uint256' },
              { internalType: 'uint256', name: 'Y', type: 'uint256' },
            ],
            internalType: 'struct BN254.G1Point[]',
            name: 'nonSignerPubkeys',
            type: 'tuple[]',
          },
          {
            components: [
              { internalType: 'uint256', name: 'X', type: 'uint256' },
              { internalType: 'uint256', name: 'Y', type: 'uint256' },
            ],
            internalType: 'struct BN254.G1Point[]',
            name: 'quorumApks',
            type: 'tuple[]',
          },
          {
            components: [
              { internalType: 'uint256[2]', name: 'X', type: 'uint256[2]' },
              { internalType: 'uint256[2]', name: 'Y', type: 'uint256[2]' },
            ],
            internalType: 'struct BN254.G2Point',
            name: 'apkG2',
            type: 'tuple',
          },
          {
            components: [
              { internalType: 'uint256', name: 'X', type: 'uint256' },
              { internalType: 'uint256', name: 'Y', type: 'uint256' },
            ],
            internalType: 'struct BN254.G1Point',
            name: 'sigma',
            type: 'tuple',
          },
          { internalType: 'uint32[]', name: 'quorumApkIndices', type: 'uint32[]' },
          { internalType: 'uint32[]', name: 'totalStakeIndices', type: 'uint32[]' },
          { internalType: 'uint32[][]', name: 'nonSignerStakeIndices', type: 'uint32[][]' },
        ],
        internalType: 'struct IBLSSignatureCheckerTypes.NonSignerStakesAndSignature',
        name: 'params',
        type: 'tuple',
      },
    ],
    name: 'checkSignatures',
    outputs: [
      {
        components: [
          { internalType: 'uint96[]', name: 'signedStakeForQuorum', type: 'uint96[]' },
          { internalType: 'uint96[]', name: 'totalStakeForQuorum', type: 'uint96[]' },
        ],
        internalType: 'struct IBLSSignatureCheckerTypes.QuorumStakeTotals',
        name: '',
        type: 'tuple',
      },
      { internalType: 'bytes32', name: '', type: 'bytes32' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'bytes32', name: 'taskId', type: 'bytes32' },
          { internalType: 'bytes', name: 'wasmArgs', type: 'bytes' },
          { internalType: 'address', name: 'policyClient', type: 'address' },
          {
            components: [
              { internalType: 'address', name: 'from', type: 'address' },
              { internalType: 'address', name: 'to', type: 'address' },
              { internalType: 'uint256', name: 'value', type: 'uint256' },
              { internalType: 'bytes', name: 'data', type: 'bytes' },
              { internalType: 'uint256', name: 'chainId', type: 'uint256' },
              { internalType: 'bytes', name: 'functionSignature', type: 'bytes' },
            ],
            internalType: 'struct NewtonMessage.Intent',
            name: 'intent',
            type: 'tuple',
          },
          { internalType: 'bytes', name: 'intentSignature', type: 'bytes' },
          {
            components: [
              { internalType: 'bytes32', name: 'policyId', type: 'bytes32' },
              { internalType: 'address', name: 'policyAddress', type: 'address' },
              { internalType: 'bytes', name: 'policy', type: 'bytes' },
              {
                components: [
                  { internalType: 'bytes', name: 'wasmArgs', type: 'bytes' },
                  { internalType: 'bytes', name: 'data', type: 'bytes' },
                  { internalType: 'bytes', name: 'attestation', type: 'bytes' },
                  { internalType: 'address', name: 'policyDataAddress', type: 'address' },
                  { internalType: 'uint32', name: 'expireBlock', type: 'uint32' },
                ],
                internalType: 'struct NewtonMessage.PolicyData[]',
                name: 'policyData',
                type: 'tuple[]',
              },
            ],
            internalType: 'struct NewtonMessage.PolicyTaskData',
            name: 'policyTaskData',
            type: 'tuple',
          },
          { internalType: 'bytes', name: 'quorumNumbers', type: 'bytes' },
          { internalType: 'uint32', name: 'quorumThresholdPercentage', type: 'uint32' },
        ],
        internalType: 'struct INewtonProverTaskManager.TaskParams',
        name: 'params',
        type: 'tuple',
      },
    ],
    name: 'createNewTask',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'delegation',
    outputs: [{ internalType: 'contract IDelegationManager', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'epochBlocks',
    outputs: [{ internalType: 'uint32', name: '', type: 'uint32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'contract ISlashingRegistryCoordinator', name: 'registryCoordinator', type: 'address' },
      { internalType: 'bytes32[]', name: 'operatorIds', type: 'bytes32[]' },
    ],
    name: 'getBatchOperatorFromId',
    outputs: [{ internalType: 'address[]', name: 'operators', type: 'address[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'contract ISlashingRegistryCoordinator', name: 'registryCoordinator', type: 'address' },
      { internalType: 'address[]', name: 'operators', type: 'address[]' },
    ],
    name: 'getBatchOperatorId',
    outputs: [{ internalType: 'bytes32[]', name: 'operatorIds', type: 'bytes32[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'contract ISlashingRegistryCoordinator', name: 'registryCoordinator', type: 'address' },
      { internalType: 'uint32', name: 'referenceBlockNumber', type: 'uint32' },
      { internalType: 'bytes', name: 'quorumNumbers', type: 'bytes' },
      { internalType: 'bytes32[]', name: 'nonSignerOperatorIds', type: 'bytes32[]' },
    ],
    name: 'getCheckSignaturesIndices',
    outputs: [
      {
        components: [
          { internalType: 'uint32[]', name: 'nonSignerQuorumBitmapIndices', type: 'uint32[]' },
          { internalType: 'uint32[]', name: 'quorumApkIndices', type: 'uint32[]' },
          { internalType: 'uint32[]', name: 'totalStakeIndices', type: 'uint32[]' },
          { internalType: 'uint32[][]', name: 'nonSignerStakeIndices', type: 'uint32[][]' },
        ],
        internalType: 'struct OperatorStateRetriever.CheckSignaturesIndices',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'contract ISlashingRegistryCoordinator', name: 'registryCoordinator', type: 'address' },
      { internalType: 'bytes', name: 'quorumNumbers', type: 'bytes' },
      { internalType: 'uint32', name: 'blockNumber', type: 'uint32' },
    ],
    name: 'getOperatorState',
    outputs: [
      {
        components: [
          { internalType: 'address', name: 'operator', type: 'address' },
          { internalType: 'bytes32', name: 'operatorId', type: 'bytes32' },
          { internalType: 'uint96', name: 'stake', type: 'uint96' },
        ],
        internalType: 'struct OperatorStateRetriever.Operator[][]',
        name: '',
        type: 'tuple[][]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'contract ISlashingRegistryCoordinator', name: 'registryCoordinator', type: 'address' },
      { internalType: 'bytes32', name: 'operatorId', type: 'bytes32' },
      { internalType: 'uint32', name: 'blockNumber', type: 'uint32' },
    ],
    name: 'getOperatorState',
    outputs: [
      { internalType: 'uint256', name: '', type: 'uint256' },
      {
        components: [
          { internalType: 'address', name: 'operator', type: 'address' },
          { internalType: 'bytes32', name: 'operatorId', type: 'bytes32' },
          { internalType: 'uint96', name: 'stake', type: 'uint96' },
        ],
        internalType: 'struct OperatorStateRetriever.Operator[][]',
        name: '',
        type: 'tuple[][]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'contract ISlashingRegistryCoordinator', name: 'registryCoordinator', type: 'address' },
      { internalType: 'bytes32[]', name: 'operatorIds', type: 'bytes32[]' },
      { internalType: 'uint32', name: 'blockNumber', type: 'uint32' },
    ],
    name: 'getQuorumBitmapsAtBlockNumber',
    outputs: [{ internalType: 'uint256[]', name: '', type: 'uint256[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'initialOwner', type: 'address' },
      { internalType: 'address', name: '_aggregator', type: 'address' },
      { internalType: 'address', name: '_serviceManager', type: 'address' },
      { internalType: 'address', name: '_operatorRegistry', type: 'address' },
      { internalType: 'address', name: '_taskResponseHandler', type: 'address' },
      { internalType: 'address', name: '_challengeVerifier', type: 'address' },
      { internalType: 'address', name: '_attestationValidator', type: 'address' },
      { internalType: 'uint32', name: '_taskResponseWindowBlock', type: 'uint32' },
      { internalType: 'uint32', name: '_epochBlocks', type: 'uint32' },
    ],
    name: 'initialize',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'isDestinationChain',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'nonce',
    outputs: [{ internalType: 'uint32', name: '', type: 'uint32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'operatorRegistry',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'newPausedStatus', type: 'uint256' }],
    name: 'pause',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  { inputs: [], name: 'pauseAll', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  {
    inputs: [{ internalType: 'uint8', name: 'index', type: 'uint8' }],
    name: 'paused',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'paused',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'pauserRegistry',
    outputs: [{ internalType: 'contract IPauserRegistry', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'bytes32', name: 'taskId', type: 'bytes32' },
          { internalType: 'bytes32', name: 'policyId', type: 'bytes32' },
          { internalType: 'address', name: 'policyClient', type: 'address' },
          { internalType: 'uint32', name: 'nonce', type: 'uint32' },
          { internalType: 'uint32', name: 'taskCreatedBlock', type: 'uint32' },
          { internalType: 'uint32', name: 'quorumThresholdPercentage', type: 'uint32' },
          {
            components: [
              { internalType: 'address', name: 'from', type: 'address' },
              { internalType: 'address', name: 'to', type: 'address' },
              { internalType: 'uint256', name: 'value', type: 'uint256' },
              { internalType: 'bytes', name: 'data', type: 'bytes' },
              { internalType: 'uint256', name: 'chainId', type: 'uint256' },
              { internalType: 'bytes', name: 'functionSignature', type: 'bytes' },
            ],
            internalType: 'struct NewtonMessage.Intent',
            name: 'intent',
            type: 'tuple',
          },
          { internalType: 'bytes', name: 'intentSignature', type: 'bytes' },
          {
            components: [
              { internalType: 'bytes32', name: 'policyId', type: 'bytes32' },
              { internalType: 'address', name: 'policyAddress', type: 'address' },
              { internalType: 'bytes', name: 'policy', type: 'bytes' },
              {
                components: [
                  { internalType: 'bytes', name: 'wasmArgs', type: 'bytes' },
                  { internalType: 'bytes', name: 'data', type: 'bytes' },
                  { internalType: 'bytes', name: 'attestation', type: 'bytes' },
                  { internalType: 'address', name: 'policyDataAddress', type: 'address' },
                  { internalType: 'uint32', name: 'expireBlock', type: 'uint32' },
                ],
                internalType: 'struct NewtonMessage.PolicyData[]',
                name: 'policyData',
                type: 'tuple[]',
              },
            ],
            internalType: 'struct NewtonMessage.PolicyTaskData',
            name: 'policyTaskData',
            type: 'tuple',
          },
          {
            components: [
              { internalType: 'bytes', name: 'policyParams', type: 'bytes' },
              { internalType: 'uint32', name: 'expireAfter', type: 'uint32' },
            ],
            internalType: 'struct INewtonPolicy.PolicyConfig',
            name: 'policyConfig',
            type: 'tuple',
          },
          { internalType: 'bytes', name: 'quorumNumbers', type: 'bytes' },
        ],
        internalType: 'struct INewtonProverTaskManager.Task',
        name: 'task',
        type: 'tuple',
      },
      {
        components: [
          { internalType: 'bytes32', name: 'taskId', type: 'bytes32' },
          { internalType: 'address', name: 'policyClient', type: 'address' },
          { internalType: 'bytes32', name: 'policyId', type: 'bytes32' },
          { internalType: 'address', name: 'policyAddress', type: 'address' },
          {
            components: [
              { internalType: 'address', name: 'from', type: 'address' },
              { internalType: 'address', name: 'to', type: 'address' },
              { internalType: 'uint256', name: 'value', type: 'uint256' },
              { internalType: 'bytes', name: 'data', type: 'bytes' },
              { internalType: 'uint256', name: 'chainId', type: 'uint256' },
              { internalType: 'bytes', name: 'functionSignature', type: 'bytes' },
            ],
            internalType: 'struct NewtonMessage.Intent',
            name: 'intent',
            type: 'tuple',
          },
          { internalType: 'bytes', name: 'intentSignature', type: 'bytes' },
          { internalType: 'bytes', name: 'evaluationResult', type: 'bytes' },
        ],
        internalType: 'struct INewtonProverTaskManager.TaskResponse',
        name: 'taskResponse',
        type: 'tuple',
      },
      {
        components: [
          { internalType: 'uint32', name: 'referenceBlock', type: 'uint32' },
          { internalType: 'uint32', name: 'responseExpireBlock', type: 'uint32' },
          { internalType: 'bytes32', name: 'hashOfNonSigners', type: 'bytes32' },
          { internalType: 'bytes', name: 'signatureData', type: 'bytes' },
        ],
        internalType: 'struct INewtonProverTaskManager.ResponseCertificate',
        name: 'responseCertificate',
        type: 'tuple',
      },
      {
        components: [
          { internalType: 'bytes32', name: 'taskId', type: 'bytes32' },
          { internalType: 'bytes', name: 'proof', type: 'bytes' },
          { internalType: 'bytes', name: 'data', type: 'bytes' },
        ],
        internalType: 'struct INewtonProverTaskManager.ChallengeData',
        name: 'challenge',
        type: 'tuple',
      },
      {
        components: [
          { internalType: 'uint256', name: 'X', type: 'uint256' },
          { internalType: 'uint256', name: 'Y', type: 'uint256' },
        ],
        internalType: 'struct BN254.G1Point[]',
        name: 'pubkeysOfNonSigningOperators',
        type: 'tuple[]',
      },
    ],
    name: 'raiseAndResolveChallenge',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'registryCoordinator',
    outputs: [{ internalType: 'contract ISlashingRegistryCoordinator', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  { inputs: [], name: 'renounceOwnership', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  {
    inputs: [
      {
        components: [
          { internalType: 'bytes32', name: 'taskId', type: 'bytes32' },
          { internalType: 'bytes32', name: 'policyId', type: 'bytes32' },
          { internalType: 'address', name: 'policyClient', type: 'address' },
          { internalType: 'uint32', name: 'nonce', type: 'uint32' },
          { internalType: 'uint32', name: 'taskCreatedBlock', type: 'uint32' },
          { internalType: 'uint32', name: 'quorumThresholdPercentage', type: 'uint32' },
          {
            components: [
              { internalType: 'address', name: 'from', type: 'address' },
              { internalType: 'address', name: 'to', type: 'address' },
              { internalType: 'uint256', name: 'value', type: 'uint256' },
              { internalType: 'bytes', name: 'data', type: 'bytes' },
              { internalType: 'uint256', name: 'chainId', type: 'uint256' },
              { internalType: 'bytes', name: 'functionSignature', type: 'bytes' },
            ],
            internalType: 'struct NewtonMessage.Intent',
            name: 'intent',
            type: 'tuple',
          },
          { internalType: 'bytes', name: 'intentSignature', type: 'bytes' },
          {
            components: [
              { internalType: 'bytes32', name: 'policyId', type: 'bytes32' },
              { internalType: 'address', name: 'policyAddress', type: 'address' },
              { internalType: 'bytes', name: 'policy', type: 'bytes' },
              {
                components: [
                  { internalType: 'bytes', name: 'wasmArgs', type: 'bytes' },
                  { internalType: 'bytes', name: 'data', type: 'bytes' },
                  { internalType: 'bytes', name: 'attestation', type: 'bytes' },
                  { internalType: 'address', name: 'policyDataAddress', type: 'address' },
                  { internalType: 'uint32', name: 'expireBlock', type: 'uint32' },
                ],
                internalType: 'struct NewtonMessage.PolicyData[]',
                name: 'policyData',
                type: 'tuple[]',
              },
            ],
            internalType: 'struct NewtonMessage.PolicyTaskData',
            name: 'policyTaskData',
            type: 'tuple',
          },
          {
            components: [
              { internalType: 'bytes', name: 'policyParams', type: 'bytes' },
              { internalType: 'uint32', name: 'expireAfter', type: 'uint32' },
            ],
            internalType: 'struct INewtonPolicy.PolicyConfig',
            name: 'policyConfig',
            type: 'tuple',
          },
          { internalType: 'bytes', name: 'quorumNumbers', type: 'bytes' },
        ],
        internalType: 'struct INewtonProverTaskManager.Task',
        name: 'task',
        type: 'tuple',
      },
      {
        components: [
          { internalType: 'bytes32', name: 'taskId', type: 'bytes32' },
          { internalType: 'address', name: 'policyClient', type: 'address' },
          { internalType: 'bytes32', name: 'policyId', type: 'bytes32' },
          { internalType: 'address', name: 'policyAddress', type: 'address' },
          {
            components: [
              { internalType: 'address', name: 'from', type: 'address' },
              { internalType: 'address', name: 'to', type: 'address' },
              { internalType: 'uint256', name: 'value', type: 'uint256' },
              { internalType: 'bytes', name: 'data', type: 'bytes' },
              { internalType: 'uint256', name: 'chainId', type: 'uint256' },
              { internalType: 'bytes', name: 'functionSignature', type: 'bytes' },
            ],
            internalType: 'struct NewtonMessage.Intent',
            name: 'intent',
            type: 'tuple',
          },
          { internalType: 'bytes', name: 'intentSignature', type: 'bytes' },
          { internalType: 'bytes', name: 'evaluationResult', type: 'bytes' },
        ],
        internalType: 'struct INewtonProverTaskManager.TaskResponse',
        name: 'taskResponse',
        type: 'tuple',
      },
      { internalType: 'bytes', name: 'signatureData', type: 'bytes' },
    ],
    name: 'respondToTask',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'serviceManager',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'stakeRegistry',
    outputs: [{ internalType: 'contract IStakeRegistry', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: 'taskId', type: 'bytes32' }],
    name: 'taskHash',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'taskResponseHandler',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: 'taskId', type: 'bytes32' }],
    name: 'taskResponseHash',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'taskResponseWindowBlock',
    outputs: [{ internalType: 'uint32', name: '', type: 'uint32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes32', name: 'msgHash', type: 'bytes32' },
      {
        components: [
          { internalType: 'uint256', name: 'X', type: 'uint256' },
          { internalType: 'uint256', name: 'Y', type: 'uint256' },
        ],
        internalType: 'struct BN254.G1Point',
        name: 'apk',
        type: 'tuple',
      },
      {
        components: [
          { internalType: 'uint256[2]', name: 'X', type: 'uint256[2]' },
          { internalType: 'uint256[2]', name: 'Y', type: 'uint256[2]' },
        ],
        internalType: 'struct BN254.G2Point',
        name: 'apkG2',
        type: 'tuple',
      },
      {
        components: [
          { internalType: 'uint256', name: 'X', type: 'uint256' },
          { internalType: 'uint256', name: 'Y', type: 'uint256' },
        ],
        internalType: 'struct BN254.G1Point',
        name: 'sigma',
        type: 'tuple',
      },
    ],
    name: 'trySignatureAndApkVerification',
    outputs: [
      { internalType: 'bool', name: 'pairingSuccessful', type: 'bool' },
      { internalType: 'bool', name: 'siganatureIsValid', type: 'bool' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'newPausedStatus', type: 'uint256' }],
    name: 'unpause',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint32', name: '_epochBlocks', type: 'uint32' }],
    name: 'updateEpochBlocks',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint32', name: '_taskResponseWindowBlock', type: 'uint32' }],
    name: 'updateTaskResponseWindowBlock',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'bytes32', name: 'taskId', type: 'bytes32' },
          { internalType: 'bytes32', name: 'policyId', type: 'bytes32' },
          { internalType: 'address', name: 'policyClient', type: 'address' },
          { internalType: 'uint32', name: 'expiration', type: 'uint32' },
          {
            components: [
              { internalType: 'address', name: 'from', type: 'address' },
              { internalType: 'address', name: 'to', type: 'address' },
              { internalType: 'uint256', name: 'value', type: 'uint256' },
              { internalType: 'bytes', name: 'data', type: 'bytes' },
              { internalType: 'uint256', name: 'chainId', type: 'uint256' },
              { internalType: 'bytes', name: 'functionSignature', type: 'bytes' },
            ],
            internalType: 'struct NewtonMessage.Intent',
            name: 'intent',
            type: 'tuple',
          },
          { internalType: 'bytes', name: 'intentSignature', type: 'bytes' },
        ],
        internalType: 'struct NewtonMessage.Attestation',
        name: 'attestation',
        type: 'tuple',
      },
    ],
    name: 'validateAttestation',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'bytes32', name: 'taskId', type: 'bytes32' },
          { internalType: 'bytes32', name: 'policyId', type: 'bytes32' },
          { internalType: 'address', name: 'policyClient', type: 'address' },
          { internalType: 'uint32', name: 'nonce', type: 'uint32' },
          { internalType: 'uint32', name: 'taskCreatedBlock', type: 'uint32' },
          { internalType: 'uint32', name: 'quorumThresholdPercentage', type: 'uint32' },
          {
            components: [
              { internalType: 'address', name: 'from', type: 'address' },
              { internalType: 'address', name: 'to', type: 'address' },
              { internalType: 'uint256', name: 'value', type: 'uint256' },
              { internalType: 'bytes', name: 'data', type: 'bytes' },
              { internalType: 'uint256', name: 'chainId', type: 'uint256' },
              { internalType: 'bytes', name: 'functionSignature', type: 'bytes' },
            ],
            internalType: 'struct NewtonMessage.Intent',
            name: 'intent',
            type: 'tuple',
          },
          { internalType: 'bytes', name: 'intentSignature', type: 'bytes' },
          {
            components: [
              { internalType: 'bytes32', name: 'policyId', type: 'bytes32' },
              { internalType: 'address', name: 'policyAddress', type: 'address' },
              { internalType: 'bytes', name: 'policy', type: 'bytes' },
              {
                components: [
                  { internalType: 'bytes', name: 'wasmArgs', type: 'bytes' },
                  { internalType: 'bytes', name: 'data', type: 'bytes' },
                  { internalType: 'bytes', name: 'attestation', type: 'bytes' },
                  { internalType: 'address', name: 'policyDataAddress', type: 'address' },
                  { internalType: 'uint32', name: 'expireBlock', type: 'uint32' },
                ],
                internalType: 'struct NewtonMessage.PolicyData[]',
                name: 'policyData',
                type: 'tuple[]',
              },
            ],
            internalType: 'struct NewtonMessage.PolicyTaskData',
            name: 'policyTaskData',
            type: 'tuple',
          },
          {
            components: [
              { internalType: 'bytes', name: 'policyParams', type: 'bytes' },
              { internalType: 'uint32', name: 'expireAfter', type: 'uint32' },
            ],
            internalType: 'struct INewtonPolicy.PolicyConfig',
            name: 'policyConfig',
            type: 'tuple',
          },
          { internalType: 'bytes', name: 'quorumNumbers', type: 'bytes' },
        ],
        internalType: 'struct INewtonProverTaskManager.Task',
        name: 'task',
        type: 'tuple',
      },
      {
        components: [
          { internalType: 'bytes32', name: 'taskId', type: 'bytes32' },
          { internalType: 'address', name: 'policyClient', type: 'address' },
          { internalType: 'bytes32', name: 'policyId', type: 'bytes32' },
          { internalType: 'address', name: 'policyAddress', type: 'address' },
          {
            components: [
              { internalType: 'address', name: 'from', type: 'address' },
              { internalType: 'address', name: 'to', type: 'address' },
              { internalType: 'uint256', name: 'value', type: 'uint256' },
              { internalType: 'bytes', name: 'data', type: 'bytes' },
              { internalType: 'uint256', name: 'chainId', type: 'uint256' },
              { internalType: 'bytes', name: 'functionSignature', type: 'bytes' },
            ],
            internalType: 'struct NewtonMessage.Intent',
            name: 'intent',
            type: 'tuple',
          },
          { internalType: 'bytes', name: 'intentSignature', type: 'bytes' },
          { internalType: 'bytes', name: 'evaluationResult', type: 'bytes' },
        ],
        internalType: 'struct INewtonProverTaskManager.TaskResponse',
        name: 'taskResponse',
        type: 'tuple',
      },
      {
        components: [
          { internalType: 'uint32[]', name: 'nonSignerQuorumBitmapIndices', type: 'uint32[]' },
          {
            components: [
              { internalType: 'uint256', name: 'X', type: 'uint256' },
              { internalType: 'uint256', name: 'Y', type: 'uint256' },
            ],
            internalType: 'struct BN254.G1Point[]',
            name: 'nonSignerPubkeys',
            type: 'tuple[]',
          },
          {
            components: [
              { internalType: 'uint256', name: 'X', type: 'uint256' },
              { internalType: 'uint256', name: 'Y', type: 'uint256' },
            ],
            internalType: 'struct BN254.G1Point[]',
            name: 'quorumApks',
            type: 'tuple[]',
          },
          {
            components: [
              { internalType: 'uint256[2]', name: 'X', type: 'uint256[2]' },
              { internalType: 'uint256[2]', name: 'Y', type: 'uint256[2]' },
            ],
            internalType: 'struct BN254.G2Point',
            name: 'apkG2',
            type: 'tuple',
          },
          {
            components: [
              { internalType: 'uint256', name: 'X', type: 'uint256' },
              { internalType: 'uint256', name: 'Y', type: 'uint256' },
            ],
            internalType: 'struct BN254.G1Point',
            name: 'sigma',
            type: 'tuple',
          },
          { internalType: 'uint32[]', name: 'quorumApkIndices', type: 'uint32[]' },
          { internalType: 'uint32[]', name: 'totalStakeIndices', type: 'uint32[]' },
          { internalType: 'uint32[][]', name: 'nonSignerStakeIndices', type: 'uint32[][]' },
        ],
        internalType: 'struct IBLSSignatureCheckerTypes.NonSignerStakesAndSignature',
        name: 'nonSignerStakesAndSignature',
        type: 'tuple',
      },
    ],
    name: 'validateAttestationDirect',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'version',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'view',
    type: 'function',
  },
];

export type TaskRespondedLog = Log & {
  args: {
    taskResponse: {
      taskId: Hex;
      policyClient: Address;
      policyId: Hex;
      policyAddress: Address;
      intent: {
        from: Address;
        to: Address;
        value: string; // string representation of big int
        data: Hex;
        chainId: string; // string representation of big int
        functionSignature: Hex;
      };
      intentSignature: Hex;
      evaluationResult: Hex;
    };
    responseCertificate: {
      taskResponsedBlock: string;
      responseExpireBlock: string;
      hashOfNonSigners: Hex;
    };
  };
};
