import type { Address, Hex, Log } from 'viem';

export const newtonAbi = [
  {
    inputs: [
      { internalType: 'contract ISlashingRegistryCoordinator', name: '_slashingRegistryCoordinator', type: 'address' },
      { internalType: 'contract IPauserRegistry', name: '_pauserRegistry', type: 'address' },
      { internalType: 'uint32', name: '_taskResponseWindowBlock', type: 'uint32' },
    ],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  { inputs: [], name: 'AttestationAlreadySpent', type: 'error' },
  { inputs: [], name: 'AttestationExpired', type: 'error' },
  { inputs: [], name: 'AttestationHashMismatch', type: 'error' },
  { inputs: [], name: 'BitmapValueTooLarge', type: 'error' },
  { inputs: [], name: 'BytesArrayLengthTooLong', type: 'error' },
  { inputs: [], name: 'BytesArrayNotOrdered', type: 'error' },
  { inputs: [], name: 'ChallengeNotEnabled', type: 'error' },
  { inputs: [], name: 'ChallengePeriodExpired', type: 'error' },
  { inputs: [], name: 'ChallengeTaskIdMismatch', type: 'error' },
  { inputs: [], name: 'CurrentlyPaused', type: 'error' },
  { inputs: [], name: 'ECAddFailed', type: 'error' },
  { inputs: [], name: 'ECMulFailed', type: 'error' },
  { inputs: [], name: 'ExpModFailed', type: 'error' },
  { inputs: [], name: 'InputAddressZero', type: 'error' },
  { inputs: [], name: 'InputArrayLengthMismatch', type: 'error' },
  { inputs: [], name: 'InputEmptyQuorumNumbers', type: 'error' },
  { inputs: [], name: 'InputNonSignerLengthMismatch', type: 'error' },
  { inputs: [], name: 'InsufficientQuorumStake', type: 'error' },
  { inputs: [], name: 'InterfaceNotSupported', type: 'error' },
  { inputs: [], name: 'InvalidBLSPairingKey', type: 'error' },
  { inputs: [], name: 'InvalidBLSSignature', type: 'error' },
  { inputs: [], name: 'InvalidNewPausedStatus', type: 'error' },
  { inputs: [], name: 'InvalidNonSigners', type: 'error' },
  { inputs: [], name: 'InvalidPolicyAddress', type: 'error' },
  { inputs: [], name: 'InvalidPolicyClient', type: 'error' },
  { inputs: [], name: 'InvalidPolicyId', type: 'error' },
  { inputs: [], name: 'InvalidQuorumApkHash', type: 'error' },
  { inputs: [], name: 'InvalidReferenceBlocknumber', type: 'error' },
  { inputs: [], name: 'NonSignerPubkeysNotSorted', type: 'error' },
  { inputs: [], name: 'OnlyAggregator', type: 'error' },
  { inputs: [], name: 'OnlyPauser', type: 'error' },
  { inputs: [], name: 'OnlyPolicyClient', type: 'error' },
  { inputs: [], name: 'OnlyRegistryCoordinatorOwner', type: 'error' },
  { inputs: [], name: 'OnlyTaskGenerator', type: 'error' },
  { inputs: [], name: 'OnlyUnpauser', type: 'error' },
  { inputs: [], name: 'OperatorNotRegistered', type: 'error' },
  { inputs: [], name: 'PolicyAddressMismatch', type: 'error' },
  { inputs: [], name: 'PolicyDataAddressMismatch', type: 'error' },
  { inputs: [], name: 'PolicyDataAttestationFailed', type: 'error' },
  { inputs: [], name: 'PolicyDataExpired', type: 'error' },
  { inputs: [], name: 'PolicyDataLengthMismatch', type: 'error' },
  { inputs: [], name: 'PolicyIdMismatch', type: 'error' },
  { inputs: [], name: 'ScalarTooLarge', type: 'error' },
  { inputs: [], name: 'StaleStakesForbidden', type: 'error' },
  { inputs: [], name: 'TaskAlreadyResponded', type: 'error' },
  { inputs: [], name: 'TaskMismatch', type: 'error' },
  { inputs: [], name: 'TaskResponseInvalid', type: 'error' },
  { inputs: [], name: 'TaskResponseTooLate', type: 'error' },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'bytes32', name: 'taskId', type: 'bytes32' },
      {
        components: [
          { internalType: 'bytes32', name: 'taskId', type: 'bytes32' },
          { internalType: 'bytes32', name: 'policyId', type: 'bytes32' },
          { internalType: 'address', name: 'policyClient', type: 'address' },
          {
            components: [
              { internalType: 'address', name: 'from', type: 'address' },
              { internalType: 'address', name: 'to', type: 'address' },
              { internalType: 'uint256', name: 'value', type: 'uint256' },
              { internalType: 'bytes', name: 'data', type: 'bytes' },
              { internalType: 'uint256', name: 'chainId', type: 'uint256' },
              { internalType: 'bytes', name: 'functionSignature', type: 'bytes' },
            ],
            internalType: 'struct NewtonMessage.Intent',
            name: 'intent',
            type: 'tuple',
          },
          { internalType: 'uint32', name: 'expiration', type: 'uint32' },
        ],
        indexed: false,
        internalType: 'struct NewtonMessage.Attestation',
        name: 'attestation',
        type: 'tuple',
      },
    ],
    name: 'AttestationSpent',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: 'uint8', name: 'version', type: 'uint8' }],
    name: 'Initialized',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'bytes32', name: 'taskId', type: 'bytes32' },
      {
        components: [
          { internalType: 'bytes32', name: 'taskId', type: 'bytes32' },
          { internalType: 'address', name: 'policyClient', type: 'address' },
          { internalType: 'bytes32', name: 'policyId', type: 'bytes32' },
          { internalType: 'uint32', name: 'nonce', type: 'uint32' },
          {
            components: [
              { internalType: 'address', name: 'from', type: 'address' },
              { internalType: 'address', name: 'to', type: 'address' },
              { internalType: 'uint256', name: 'value', type: 'uint256' },
              { internalType: 'bytes', name: 'data', type: 'bytes' },
              { internalType: 'uint256', name: 'chainId', type: 'uint256' },
              { internalType: 'bytes', name: 'functionSignature', type: 'bytes' },
            ],
            internalType: 'struct NewtonMessage.Intent',
            name: 'intent',
            type: 'tuple',
          },
          {
            components: [
              { internalType: 'bytes32', name: 'policyId', type: 'bytes32' },
              { internalType: 'address', name: 'policyAddress', type: 'address' },
              { internalType: 'bytes', name: 'policy', type: 'bytes' },
              {
                components: [
                  { internalType: 'bytes', name: 'data', type: 'bytes' },
                  { internalType: 'bytes', name: 'attestation', type: 'bytes' },
                  { internalType: 'address', name: 'policyDataAddress', type: 'address' },
                  { internalType: 'uint32', name: 'expireBlock', type: 'uint32' },
                ],
                internalType: 'struct NewtonMessage.PolicyData[]',
                name: 'policyData',
                type: 'tuple[]',
              },
            ],
            internalType: 'struct NewtonMessage.PolicyTaskData',
            name: 'policyTaskData',
            type: 'tuple',
          },
          {
            components: [
              { internalType: 'bytes', name: 'policyParams', type: 'bytes' },
              { internalType: 'uint32', name: 'expireAfter', type: 'uint32' },
            ],
            internalType: 'struct INewtonPolicy.PolicyConfig',
            name: 'policyConfig',
            type: 'tuple',
          },
          { internalType: 'uint32', name: 'taskCreatedBlock', type: 'uint32' },
          { internalType: 'bytes', name: 'quorumNumbers', type: 'bytes' },
          { internalType: 'uint32', name: 'quorumThresholdPercentage', type: 'uint32' },
        ],
        indexed: false,
        internalType: 'struct INewtonProverTaskManager.Task',
        name: 'task',
        type: 'tuple',
      },
    ],
    name: 'NewTaskCreated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'previousOwner', type: 'address' },
      { indexed: true, internalType: 'address', name: 'newOwner', type: 'address' },
    ],
    name: 'OwnershipTransferred',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'account', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'newPausedStatus', type: 'uint256' },
    ],
    name: 'Paused',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: 'bool', name: 'value', type: 'bool' }],
    name: 'StaleStakesForbiddenUpdate',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'bytes32', name: 'taskId', type: 'bytes32' },
      { indexed: true, internalType: 'address', name: 'challenger', type: 'address' },
    ],
    name: 'TaskChallengedSuccessfully',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'bytes32', name: 'taskId', type: 'bytes32' },
      { indexed: true, internalType: 'address', name: 'challenger', type: 'address' },
    ],
    name: 'TaskChallengedUnsuccessfully',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        components: [
          { internalType: 'bytes32', name: 'taskId', type: 'bytes32' },
          { internalType: 'address', name: 'policyClient', type: 'address' },
          { internalType: 'bytes32', name: 'policyId', type: 'bytes32' },
          { internalType: 'address', name: 'policyAddress', type: 'address' },
          {
            components: [
              { internalType: 'address', name: 'from', type: 'address' },
              { internalType: 'address', name: 'to', type: 'address' },
              { internalType: 'uint256', name: 'value', type: 'uint256' },
              { internalType: 'bytes', name: 'data', type: 'bytes' },
              { internalType: 'uint256', name: 'chainId', type: 'uint256' },
              { internalType: 'bytes', name: 'functionSignature', type: 'bytes' },
            ],
            internalType: 'struct NewtonMessage.Intent',
            name: 'intent',
            type: 'tuple',
          },
          { internalType: 'bytes', name: 'evaluationResult', type: 'bytes' },
        ],
        indexed: false,
        internalType: 'struct INewtonProverTaskManager.TaskResponse',
        name: 'taskResponse',
        type: 'tuple',
      },
      {
        components: [
          { internalType: 'uint32', name: 'taskResponsedBlock', type: 'uint32' },
          { internalType: 'uint32', name: 'responseExpireBlock', type: 'uint32' },
          { internalType: 'bytes32', name: 'hashOfNonSigners', type: 'bytes32' },
        ],
        indexed: false,
        internalType: 'struct INewtonProverTaskManager.TaskResponseMetadata',
        name: 'taskResponseMetadata',
        type: 'tuple',
      },
    ],
    name: 'TaskResponded',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'account', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'newPausedStatus', type: 'uint256' },
    ],
    name: 'Unpaused',
    type: 'event',
  },
  {
    inputs: [],
    name: 'TASK_CHALLENGE_WINDOW_BLOCK',
    outputs: [{ internalType: 'uint32', name: '', type: 'uint32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'TASK_RESPONSE_WINDOW_BLOCK',
    outputs: [{ internalType: 'uint32', name: '', type: 'uint32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'WADS_TO_SLASH',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'aggregator',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    name: 'allTaskHashes',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    name: 'allTaskResponses',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'allocationManager',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    name: 'attestations',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    name: 'attestationsSpent',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'blsApkRegistry',
    outputs: [{ internalType: 'contract IBLSApkRegistry', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes32', name: 'msgHash', type: 'bytes32' },
      { internalType: 'bytes', name: 'quorumNumbers', type: 'bytes' },
      { internalType: 'uint32', name: 'referenceBlockNumber', type: 'uint32' },
      {
        components: [
          { internalType: 'uint32[]', name: 'nonSignerQuorumBitmapIndices', type: 'uint32[]' },
          {
            components: [
              { internalType: 'uint256', name: 'X', type: 'uint256' },
              { internalType: 'uint256', name: 'Y', type: 'uint256' },
            ],
            internalType: 'struct BN254.G1Point[]',
            name: 'nonSignerPubkeys',
            type: 'tuple[]',
          },
          {
            components: [
              { internalType: 'uint256', name: 'X', type: 'uint256' },
              { internalType: 'uint256', name: 'Y', type: 'uint256' },
            ],
            internalType: 'struct BN254.G1Point[]',
            name: 'quorumApks',
            type: 'tuple[]',
          },
          {
            components: [
              { internalType: 'uint256[2]', name: 'X', type: 'uint256[2]' },
              { internalType: 'uint256[2]', name: 'Y', type: 'uint256[2]' },
            ],
            internalType: 'struct BN254.G2Point',
            name: 'apkG2',
            type: 'tuple',
          },
          {
            components: [
              { internalType: 'uint256', name: 'X', type: 'uint256' },
              { internalType: 'uint256', name: 'Y', type: 'uint256' },
            ],
            internalType: 'struct BN254.G1Point',
            name: 'sigma',
            type: 'tuple',
          },
          { internalType: 'uint32[]', name: 'quorumApkIndices', type: 'uint32[]' },
          { internalType: 'uint32[]', name: 'totalStakeIndices', type: 'uint32[]' },
          { internalType: 'uint32[][]', name: 'nonSignerStakeIndices', type: 'uint32[][]' },
        ],
        internalType: 'struct IBLSSignatureCheckerTypes.NonSignerStakesAndSignature',
        name: 'params',
        type: 'tuple',
      },
    ],
    name: 'checkSignatures',
    outputs: [
      {
        components: [
          { internalType: 'uint96[]', name: 'signedStakeForQuorum', type: 'uint96[]' },
          { internalType: 'uint96[]', name: 'totalStakeForQuorum', type: 'uint96[]' },
        ],
        internalType: 'struct IBLSSignatureCheckerTypes.QuorumStakeTotals',
        name: '',
        type: 'tuple',
      },
      { internalType: 'bytes32', name: '', type: 'bytes32' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'policyClient', type: 'address' },
      {
        components: [
          { internalType: 'address', name: 'from', type: 'address' },
          { internalType: 'address', name: 'to', type: 'address' },
          { internalType: 'uint256', name: 'value', type: 'uint256' },
          { internalType: 'bytes', name: 'data', type: 'bytes' },
          { internalType: 'uint256', name: 'chainId', type: 'uint256' },
          { internalType: 'bytes', name: 'functionSignature', type: 'bytes' },
        ],
        internalType: 'struct NewtonMessage.Intent',
        name: 'intent',
        type: 'tuple',
      },
      {
        components: [
          { internalType: 'bytes32', name: 'policyId', type: 'bytes32' },
          { internalType: 'address', name: 'policyAddress', type: 'address' },
          { internalType: 'bytes', name: 'policy', type: 'bytes' },
          {
            components: [
              { internalType: 'bytes', name: 'data', type: 'bytes' },
              { internalType: 'bytes', name: 'attestation', type: 'bytes' },
              { internalType: 'address', name: 'policyDataAddress', type: 'address' },
              { internalType: 'uint32', name: 'expireBlock', type: 'uint32' },
            ],
            internalType: 'struct NewtonMessage.PolicyData[]',
            name: 'policyData',
            type: 'tuple[]',
          },
        ],
        internalType: 'struct NewtonMessage.PolicyTaskData',
        name: 'policyTaskData',
        type: 'tuple',
      },
      { internalType: 'bytes', name: 'quorumNumbers', type: 'bytes' },
      { internalType: 'uint32', name: 'quorumThresholdPercentage', type: 'uint32' },
    ],
    name: 'createNewTask',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'delegation',
    outputs: [{ internalType: 'contract IDelegationManager', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'generator',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'contract ISlashingRegistryCoordinator', name: 'registryCoordinator', type: 'address' },
      { internalType: 'bytes32[]', name: 'operatorIds', type: 'bytes32[]' },
    ],
    name: 'getBatchOperatorFromId',
    outputs: [{ internalType: 'address[]', name: 'operators', type: 'address[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'contract ISlashingRegistryCoordinator', name: 'registryCoordinator', type: 'address' },
      { internalType: 'address[]', name: 'operators', type: 'address[]' },
    ],
    name: 'getBatchOperatorId',
    outputs: [{ internalType: 'bytes32[]', name: 'operatorIds', type: 'bytes32[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'contract ISlashingRegistryCoordinator', name: 'registryCoordinator', type: 'address' },
      { internalType: 'uint32', name: 'referenceBlockNumber', type: 'uint32' },
      { internalType: 'bytes', name: 'quorumNumbers', type: 'bytes' },
      { internalType: 'bytes32[]', name: 'nonSignerOperatorIds', type: 'bytes32[]' },
    ],
    name: 'getCheckSignaturesIndices',
    outputs: [
      {
        components: [
          { internalType: 'uint32[]', name: 'nonSignerQuorumBitmapIndices', type: 'uint32[]' },
          { internalType: 'uint32[]', name: 'quorumApkIndices', type: 'uint32[]' },
          { internalType: 'uint32[]', name: 'totalStakeIndices', type: 'uint32[]' },
          { internalType: 'uint32[][]', name: 'nonSignerStakeIndices', type: 'uint32[][]' },
        ],
        internalType: 'struct OperatorStateRetriever.CheckSignaturesIndices',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'contract ISlashingRegistryCoordinator', name: 'registryCoordinator', type: 'address' },
      { internalType: 'bytes', name: 'quorumNumbers', type: 'bytes' },
      { internalType: 'uint32', name: 'blockNumber', type: 'uint32' },
    ],
    name: 'getOperatorState',
    outputs: [
      {
        components: [
          { internalType: 'address', name: 'operator', type: 'address' },
          { internalType: 'bytes32', name: 'operatorId', type: 'bytes32' },
          { internalType: 'uint96', name: 'stake', type: 'uint96' },
        ],
        internalType: 'struct OperatorStateRetriever.Operator[][]',
        name: '',
        type: 'tuple[][]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'contract ISlashingRegistryCoordinator', name: 'registryCoordinator', type: 'address' },
      { internalType: 'bytes32', name: 'operatorId', type: 'bytes32' },
      { internalType: 'uint32', name: 'blockNumber', type: 'uint32' },
    ],
    name: 'getOperatorState',
    outputs: [
      { internalType: 'uint256', name: '', type: 'uint256' },
      {
        components: [
          { internalType: 'address', name: 'operator', type: 'address' },
          { internalType: 'bytes32', name: 'operatorId', type: 'bytes32' },
          { internalType: 'uint96', name: 'stake', type: 'uint96' },
        ],
        internalType: 'struct OperatorStateRetriever.Operator[][]',
        name: '',
        type: 'tuple[][]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'contract ISlashingRegistryCoordinator', name: 'registryCoordinator', type: 'address' },
      { internalType: 'bytes32[]', name: 'operatorIds', type: 'bytes32[]' },
      { internalType: 'uint32', name: 'blockNumber', type: 'uint32' },
    ],
    name: 'getQuorumBitmapsAtBlockNumber',
    outputs: [{ internalType: 'uint256[]', name: '', type: 'uint256[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getTaskResponseWindowBlock',
    outputs: [{ internalType: 'uint32', name: '', type: 'uint32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'initialOwner', type: 'address' },
      { internalType: 'address', name: '_aggregator', type: 'address' },
      { internalType: 'address', name: '_generator', type: 'address' },
      { internalType: 'address', name: '_allocationManager', type: 'address' },
      { internalType: 'address', name: '_slasher', type: 'address' },
      { internalType: 'address', name: '_serviceManager', type: 'address' },
    ],
    name: 'initialize',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'instantSlasher',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'isChallengeEnabled',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'latestNonce',
    outputs: [{ internalType: 'uint32', name: '', type: 'uint32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'nonce',
    outputs: [{ internalType: 'uint32', name: '', type: 'uint32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'newPausedStatus', type: 'uint256' }],
    name: 'pause',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  { inputs: [], name: 'pauseAll', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  {
    inputs: [{ internalType: 'uint8', name: 'index', type: 'uint8' }],
    name: 'paused',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'paused',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'pauserRegistry',
    outputs: [{ internalType: 'contract IPauserRegistry', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'bytes32', name: 'taskId', type: 'bytes32' },
          { internalType: 'address', name: 'policyClient', type: 'address' },
          { internalType: 'bytes32', name: 'policyId', type: 'bytes32' },
          { internalType: 'uint32', name: 'nonce', type: 'uint32' },
          {
            components: [
              { internalType: 'address', name: 'from', type: 'address' },
              { internalType: 'address', name: 'to', type: 'address' },
              { internalType: 'uint256', name: 'value', type: 'uint256' },
              { internalType: 'bytes', name: 'data', type: 'bytes' },
              { internalType: 'uint256', name: 'chainId', type: 'uint256' },
              { internalType: 'bytes', name: 'functionSignature', type: 'bytes' },
            ],
            internalType: 'struct NewtonMessage.Intent',
            name: 'intent',
            type: 'tuple',
          },
          {
            components: [
              { internalType: 'bytes32', name: 'policyId', type: 'bytes32' },
              { internalType: 'address', name: 'policyAddress', type: 'address' },
              { internalType: 'bytes', name: 'policy', type: 'bytes' },
              {
                components: [
                  { internalType: 'bytes', name: 'data', type: 'bytes' },
                  { internalType: 'bytes', name: 'attestation', type: 'bytes' },
                  { internalType: 'address', name: 'policyDataAddress', type: 'address' },
                  { internalType: 'uint32', name: 'expireBlock', type: 'uint32' },
                ],
                internalType: 'struct NewtonMessage.PolicyData[]',
                name: 'policyData',
                type: 'tuple[]',
              },
            ],
            internalType: 'struct NewtonMessage.PolicyTaskData',
            name: 'policyTaskData',
            type: 'tuple',
          },
          {
            components: [
              { internalType: 'bytes', name: 'policyParams', type: 'bytes' },
              { internalType: 'uint32', name: 'expireAfter', type: 'uint32' },
            ],
            internalType: 'struct INewtonPolicy.PolicyConfig',
            name: 'policyConfig',
            type: 'tuple',
          },
          { internalType: 'uint32', name: 'taskCreatedBlock', type: 'uint32' },
          { internalType: 'bytes', name: 'quorumNumbers', type: 'bytes' },
          { internalType: 'uint32', name: 'quorumThresholdPercentage', type: 'uint32' },
        ],
        internalType: 'struct INewtonProverTaskManager.Task',
        name: 'task',
        type: 'tuple',
      },
      {
        components: [
          { internalType: 'bytes32', name: 'taskId', type: 'bytes32' },
          { internalType: 'address', name: 'policyClient', type: 'address' },
          { internalType: 'bytes32', name: 'policyId', type: 'bytes32' },
          { internalType: 'address', name: 'policyAddress', type: 'address' },
          {
            components: [
              { internalType: 'address', name: 'from', type: 'address' },
              { internalType: 'address', name: 'to', type: 'address' },
              { internalType: 'uint256', name: 'value', type: 'uint256' },
              { internalType: 'bytes', name: 'data', type: 'bytes' },
              { internalType: 'uint256', name: 'chainId', type: 'uint256' },
              { internalType: 'bytes', name: 'functionSignature', type: 'bytes' },
            ],
            internalType: 'struct NewtonMessage.Intent',
            name: 'intent',
            type: 'tuple',
          },
          { internalType: 'bytes', name: 'evaluationResult', type: 'bytes' },
        ],
        internalType: 'struct INewtonProverTaskManager.TaskResponse',
        name: 'taskResponse',
        type: 'tuple',
      },
      {
        components: [
          { internalType: 'uint32', name: 'taskResponsedBlock', type: 'uint32' },
          { internalType: 'uint32', name: 'responseExpireBlock', type: 'uint32' },
          { internalType: 'bytes32', name: 'hashOfNonSigners', type: 'bytes32' },
        ],
        internalType: 'struct INewtonProverTaskManager.TaskResponseMetadata',
        name: 'taskResponseMetadata',
        type: 'tuple',
      },
      {
        components: [
          { internalType: 'bytes32', name: 'taskId', type: 'bytes32' },
          { internalType: 'bytes', name: 'proof', type: 'bytes' },
          { internalType: 'bytes', name: 'data', type: 'bytes' },
        ],
        internalType: 'struct INewtonProverTaskManager.ChallengeData',
        name: 'challenge',
        type: 'tuple',
      },
      {
        components: [
          { internalType: 'uint256', name: 'X', type: 'uint256' },
          { internalType: 'uint256', name: 'Y', type: 'uint256' },
        ],
        internalType: 'struct BN254.G1Point[]',
        name: 'pubkeysOfNonSigningOperators',
        type: 'tuple[]',
      },
    ],
    name: 'raiseAndResolveChallenge',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'registryCoordinator',
    outputs: [{ internalType: 'contract ISlashingRegistryCoordinator', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  { inputs: [], name: 'renounceOwnership', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  {
    inputs: [
      {
        components: [
          { internalType: 'bytes32', name: 'taskId', type: 'bytes32' },
          { internalType: 'address', name: 'policyClient', type: 'address' },
          { internalType: 'bytes32', name: 'policyId', type: 'bytes32' },
          { internalType: 'uint32', name: 'nonce', type: 'uint32' },
          {
            components: [
              { internalType: 'address', name: 'from', type: 'address' },
              { internalType: 'address', name: 'to', type: 'address' },
              { internalType: 'uint256', name: 'value', type: 'uint256' },
              { internalType: 'bytes', name: 'data', type: 'bytes' },
              { internalType: 'uint256', name: 'chainId', type: 'uint256' },
              { internalType: 'bytes', name: 'functionSignature', type: 'bytes' },
            ],
            internalType: 'struct NewtonMessage.Intent',
            name: 'intent',
            type: 'tuple',
          },
          {
            components: [
              { internalType: 'bytes32', name: 'policyId', type: 'bytes32' },
              { internalType: 'address', name: 'policyAddress', type: 'address' },
              { internalType: 'bytes', name: 'policy', type: 'bytes' },
              {
                components: [
                  { internalType: 'bytes', name: 'data', type: 'bytes' },
                  { internalType: 'bytes', name: 'attestation', type: 'bytes' },
                  { internalType: 'address', name: 'policyDataAddress', type: 'address' },
                  { internalType: 'uint32', name: 'expireBlock', type: 'uint32' },
                ],
                internalType: 'struct NewtonMessage.PolicyData[]',
                name: 'policyData',
                type: 'tuple[]',
              },
            ],
            internalType: 'struct NewtonMessage.PolicyTaskData',
            name: 'policyTaskData',
            type: 'tuple',
          },
          {
            components: [
              { internalType: 'bytes', name: 'policyParams', type: 'bytes' },
              { internalType: 'uint32', name: 'expireAfter', type: 'uint32' },
            ],
            internalType: 'struct INewtonPolicy.PolicyConfig',
            name: 'policyConfig',
            type: 'tuple',
          },
          { internalType: 'uint32', name: 'taskCreatedBlock', type: 'uint32' },
          { internalType: 'bytes', name: 'quorumNumbers', type: 'bytes' },
          { internalType: 'uint32', name: 'quorumThresholdPercentage', type: 'uint32' },
        ],
        internalType: 'struct INewtonProverTaskManager.Task',
        name: 'task',
        type: 'tuple',
      },
      {
        components: [
          { internalType: 'bytes32', name: 'taskId', type: 'bytes32' },
          { internalType: 'address', name: 'policyClient', type: 'address' },
          { internalType: 'bytes32', name: 'policyId', type: 'bytes32' },
          { internalType: 'address', name: 'policyAddress', type: 'address' },
          {
            components: [
              { internalType: 'address', name: 'from', type: 'address' },
              { internalType: 'address', name: 'to', type: 'address' },
              { internalType: 'uint256', name: 'value', type: 'uint256' },
              { internalType: 'bytes', name: 'data', type: 'bytes' },
              { internalType: 'uint256', name: 'chainId', type: 'uint256' },
              { internalType: 'bytes', name: 'functionSignature', type: 'bytes' },
            ],
            internalType: 'struct NewtonMessage.Intent',
            name: 'intent',
            type: 'tuple',
          },
          { internalType: 'bytes', name: 'evaluationResult', type: 'bytes' },
        ],
        internalType: 'struct INewtonProverTaskManager.TaskResponse',
        name: 'taskResponse',
        type: 'tuple',
      },
      {
        components: [
          { internalType: 'uint32[]', name: 'nonSignerQuorumBitmapIndices', type: 'uint32[]' },
          {
            components: [
              { internalType: 'uint256', name: 'X', type: 'uint256' },
              { internalType: 'uint256', name: 'Y', type: 'uint256' },
            ],
            internalType: 'struct BN254.G1Point[]',
            name: 'nonSignerPubkeys',
            type: 'tuple[]',
          },
          {
            components: [
              { internalType: 'uint256', name: 'X', type: 'uint256' },
              { internalType: 'uint256', name: 'Y', type: 'uint256' },
            ],
            internalType: 'struct BN254.G1Point[]',
            name: 'quorumApks',
            type: 'tuple[]',
          },
          {
            components: [
              { internalType: 'uint256[2]', name: 'X', type: 'uint256[2]' },
              { internalType: 'uint256[2]', name: 'Y', type: 'uint256[2]' },
            ],
            internalType: 'struct BN254.G2Point',
            name: 'apkG2',
            type: 'tuple',
          },
          {
            components: [
              { internalType: 'uint256', name: 'X', type: 'uint256' },
              { internalType: 'uint256', name: 'Y', type: 'uint256' },
            ],
            internalType: 'struct BN254.G1Point',
            name: 'sigma',
            type: 'tuple',
          },
          { internalType: 'uint32[]', name: 'quorumApkIndices', type: 'uint32[]' },
          { internalType: 'uint32[]', name: 'totalStakeIndices', type: 'uint32[]' },
          { internalType: 'uint32[][]', name: 'nonSignerStakeIndices', type: 'uint32[][]' },
        ],
        internalType: 'struct IBLSSignatureCheckerTypes.NonSignerStakesAndSignature',
        name: 'nonSignerStakesAndSignature',
        type: 'tuple',
      },
    ],
    name: 'respondToTask',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'serviceManager',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bool', name: '_isChallengeEnabled', type: 'bool' }],
    name: 'setIsChallengeEnabled',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bool', name: 'value', type: 'bool' }],
    name: 'setStaleStakesForbidden',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'stakeRegistry',
    outputs: [{ internalType: 'contract IStakeRegistry', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'staleStakesForbidden',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    name: 'taskSuccesfullyChallenged',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes32', name: 'msgHash', type: 'bytes32' },
      {
        components: [
          { internalType: 'uint256', name: 'X', type: 'uint256' },
          { internalType: 'uint256', name: 'Y', type: 'uint256' },
        ],
        internalType: 'struct BN254.G1Point',
        name: 'apk',
        type: 'tuple',
      },
      {
        components: [
          { internalType: 'uint256[2]', name: 'X', type: 'uint256[2]' },
          { internalType: 'uint256[2]', name: 'Y', type: 'uint256[2]' },
        ],
        internalType: 'struct BN254.G2Point',
        name: 'apkG2',
        type: 'tuple',
      },
      {
        components: [
          { internalType: 'uint256', name: 'X', type: 'uint256' },
          { internalType: 'uint256', name: 'Y', type: 'uint256' },
        ],
        internalType: 'struct BN254.G1Point',
        name: 'sigma',
        type: 'tuple',
      },
    ],
    name: 'trySignatureAndApkVerification',
    outputs: [
      { internalType: 'bool', name: 'pairingSuccessful', type: 'bool' },
      { internalType: 'bool', name: 'siganatureIsValid', type: 'bool' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'newPausedStatus', type: 'uint256' }],
    name: 'unpause',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'bytes32', name: 'taskId', type: 'bytes32' },
          { internalType: 'bytes32', name: 'policyId', type: 'bytes32' },
          { internalType: 'address', name: 'policyClient', type: 'address' },
          {
            components: [
              { internalType: 'address', name: 'from', type: 'address' },
              { internalType: 'address', name: 'to', type: 'address' },
              { internalType: 'uint256', name: 'value', type: 'uint256' },
              { internalType: 'bytes', name: 'data', type: 'bytes' },
              { internalType: 'uint256', name: 'chainId', type: 'uint256' },
              { internalType: 'bytes', name: 'functionSignature', type: 'bytes' },
            ],
            internalType: 'struct NewtonMessage.Intent',
            name: 'intent',
            type: 'tuple',
          },
          { internalType: 'uint32', name: 'expiration', type: 'uint32' },
        ],
        internalType: 'struct NewtonMessage.Attestation',
        name: 'attestation',
        type: 'tuple',
      },
    ],
    name: 'validateAttestation',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
];

export type TaskRespondedLog = Log & {
  args: {
    taskResponse: {
      taskId: Hex;
      policyClient: Address;
      policyId: Hex;
      policyAddress: Address;
      intent: {
        from: Address;
        to: Address;
        value: bigint;
        data: Hex;
        chainId: bigint;
        functionSignature: Hex;
      };
      evaluationResult: Hex;
    };
    taskResponseMetadata: {
      taskResponsedBlock: number;
      responseExpireBlock: number;
      hashOfNonSigners: Hex;
    };
  };
};
